<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MLM2 - Ans</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="MLM2_Ans_files/libs/clipboard/clipboard.min.js"></script>
<script src="MLM2_Ans_files/libs/quarto-html/quarto.js"></script>
<script src="MLM2_Ans_files/libs/quarto-html/popper.min.js"></script>
<script src="MLM2_Ans_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MLM2_Ans_files/libs/quarto-html/anchor.min.js"></script>
<link href="MLM2_Ans_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MLM2_Ans_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="MLM2_Ans_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MLM2_Ans_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MLM2_Ans_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lab-1-mlm" id="toc-lab-1-mlm" class="nav-link active" data-scroll-target="#lab-1-mlm">Lab 1: MLM</a>
  <ul class="collapse">
  <li><a href="#load-packages" id="toc-load-packages" class="nav-link" data-scroll-target="#load-packages">Load packages</a></li>
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data">Load data</a></li>
  </ul></li>
  <li><a href="#lab-1" id="toc-lab-1" class="nav-link" data-scroll-target="#lab-1">Lab 1</a>
  <ul class="collapse">
  <li><a href="#data-structure" id="toc-data-structure" class="nav-link" data-scroll-target="#data-structure">Data structure</a></li>
  <li><a href="#deviation-code-0.5--0.5-aka-effect-code-for-the-treatment-variable" id="toc-deviation-code-0.5--0.5-aka-effect-code-for-the-treatment-variable" class="nav-link" data-scroll-target="#deviation-code-0.5--0.5-aka-effect-code-for-the-treatment-variable">2. Deviation code (0.5, -0.5), aka effect code for the treatment variable</a></li>
  <li><a href="#group-mean-center-ppvt_fallk" id="toc-group-mean-center-ppvt_fallk" class="nav-link" data-scroll-target="#group-mean-center-ppvt_fallk">3. Group mean center <code>PPVT_Fallk</code></a></li>
  <li><a href="#visualizations" id="toc-visualizations" class="nav-link" data-scroll-target="#visualizations">Visualizations</a></li>
  <li><a href="#model-comparisons" id="toc-model-comparisons" class="nav-link" data-scroll-target="#model-comparisons">Model comparisons</a></li>
  <li><a href="#model-interpretation" id="toc-model-interpretation" class="nav-link" data-scroll-target="#model-interpretation">Model interpretation</a></li>
  <li><a href="#model-fit" id="toc-model-fit" class="nav-link" data-scroll-target="#model-fit">Model fit</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  <li><a href="#reporting-results" id="toc-reporting-results" class="nav-link" data-scroll-target="#reporting-results">Reporting Results</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">MLM2 - Ans</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
<p class="subtitle lead">Advanced Statistics in Psychology</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="lab-1-mlm" class="level1">
<h1>Lab 1: MLM</h1>
<p>Today’s lab uses data from a study conducted by Coyne et al.&nbsp;(2019), which examined the impact of a high-quality, evidence-based vocabulary instruction intervention in kindergarten. The data consists of <strong>1,428 students</strong> who were <strong>nested in 233 clusters</strong> or classrooms (<code>clu_id</code>).</p>
<p>In the sample of at-risk youth in the classroom (N = 6), half were allocated to <strong>treatment</strong> and the other half to <strong>control</strong>. The treatment group received supplemental small-group vocabulary instruction in addition to the whole-group instruction, while the control group received only whole-group vocabulary instruction. Since the observations were not independent (due to students being nested within classrooms), the researchers needed to account for this in their analysis.</p>
<p><strong><em>The main question that the researchers aimed to answer was whether the supplemental small-group kindergarten vocabulary instruction intervention increased students’ knowledge of the vocabulary words taught in the intervention.</em></strong> To measure vocabulary knowledge, the researchers used an ETW (<code>ETW_SpringK</code>) assessment, which evaluated students’ ability to explain the meaning of a given word. The assessment was administered after the intervention concluded, in the spring of kindergarten. In the sample, ETW scores ranged from 0 to 52 (the maximum score), with a mean of 13.65 and a standard deviation of 11.10. To answer the research question, the researchers used two fixed effects and their interaction: TRT (1 = treatment and 0 = control) and PPVT (Peabody Picture Vocabulary Test, which measures students’ vocabulary before the intervention; <code>PPVT_FallK</code>).</p>
<p><em>Coyne, M. D., McCoach, D. B., Ware, S., Austin, C. R., Loftus-Rattan, S. M., &amp; Baker, D. L. (2019). Racing Against the Vocabulary Gap: Matthew Effects in Early Vocabulary Instruction and Intervention. Exceptional Children</em>, 85(2), 163–179. <a href="https://doi.org/10.1177/0014402918789162" class="uri">https://doi.org/10.1177/0014402918789162</a></p>
<section id="load-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-packages">Load packages</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fill in packages you need as you go here</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># data wrangling</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr) <span class="co"># nice tables</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co"># combine figures</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4) <span class="co"># fit mixed models</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest) <span class="co"># mixed models</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed) <span class="co"># tidy output of mixed models</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex) <span class="co"># fit mixed models for lrt test</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans) <span class="co"># marginal means</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects) <span class="co"># marginal means</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrain) <span class="co"># rain plots</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(easystats) <span class="co"># nice ecosystem of packages</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="load-data" class="level2">
<h2 class="anchored" data-anchor-id="load-data">Load data</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in data file</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Ch3_MLM_R.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="lab-1" class="level1">
<h1>Lab 1</h1>
<section id="data-structure" class="level2">
<h2 class="anchored" data-anchor-id="data-structure">Data structure</h2>
<p>Q1. What are the Level 1 and Level 2 variables in this study? How many units are in Level 1? Level 2? Are the fixed effects at Level 1 or Level 2?</p>
<p>Q2. What are the Level 1 and Level 2 variables in this study? How many units are in Level 1? Level 2? Are the fixed effects at Level 1 or Level 2?</p>
<p><u><strong>Answers:</strong></u></p>
<ul>
<li><p><u><strong>Level 1 variables: <code>ETW_SpringK</code>, <code>TRT</code>, and <code>PPVT_FallK</code>.</strong></u></p></li>
<li><p><u><strong>There are 1,427 units in Level 1. There are 222 units in Level 2.</strong></u></p></li>
<li><p><u><strong>The fixed effects are at Level 1 because they pertain to the individual student-level variables and their interactions.</strong></u></p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Computing Dataset Statistics:</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># assuming 'data' is the dataframe and 'clu_id' identifies the clusters/classrooms</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(clu_id) <span class="sc">%&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">N_students =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">N_clusters =</span> <span class="fu">n</span>(),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_students =</span> <span class="fu">sum</span>(N_students),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_students_per_classroom =</span> <span class="fu">mean</span>(N_students),</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD_students_per_classroom =</span> <span class="fu">sd</span>(N_students),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_students_in_classroom =</span> <span class="fu">min</span>(N_students),</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_students_in_classroom =</span> <span class="fu">max</span>(N_students)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the values to variables for easier printing</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>n_clusters <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>N_clusters</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>total_students <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>Total_students</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>average_students <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>Average_students_per_classroom</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>sd_students <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>SD_students_per_classroom</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>min_students <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>Min_students_in_classroom</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>max_students <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>Max_students_in_classroom</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Number of clusters (classrooms):"</span>, n_clusters, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Number of clusters (classrooms): 222 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Total number of students:"</span>, total_students, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Total number of students: 1427 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Average number of students per classroom:"</span>, <span class="fu">round</span>(average_students, <span class="dv">1</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Average number of students per classroom: 6.4 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Standard deviation of students per classroom:"</span>, <span class="fu">round</span>(sd_students, <span class="dv">1</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Standard deviation of students per classroom: 2.2 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Minimum number of students in a classroom:"</span>, min_students, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Minimum number of students in a classroom: 2 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Maximum number of students in a classroom:"</span>, max_students, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Maximum number of students in a classroom: 18 </code></pre>
</div>
</div>
</section>
<section id="deviation-code-0.5--0.5-aka-effect-code-for-the-treatment-variable" class="level2">
<h2 class="anchored" data-anchor-id="deviation-code-0.5--0.5-aka-effect-code-for-the-treatment-variable">2. Deviation code (0.5, -0.5), aka effect code for the treatment variable</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>NOTE</strong>: Deviation/Effect coding is one way to recode categorical variables for regression analysis. They transform the treatment variable (TRT) from: treatment → 0.5 control → -0.5</p>
<p>Remember that different ways of coding categorical variables do not actually influence the results/ predictions. But they can influence how we interpret coefficients.</p>
<p>Now, with deviation coding (-0.5,0.5), here: Intercept = grand mean across all groups Treatment coefficient = difference between groups (divided by 2)</p>
<p>With dummy coding (0/1), it’d be: Intercept = mean of reference group Treatment coefficient = difference from reference group</p>
<p>The key advantage? When interpreting interactions, deviation coding makes results more intuitive since coefficients show deviations from overall means (or overall main effect) rather than from a reference group (which may not always be clear or relevant, making interpretation harder) .</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#deviation code the TRT var</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TRT =</span> <span class="fu">ifelse</span>(TRT <span class="sc">==</span> <span class="dv">1</span>, <span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Note, one can also use contr.sum to instantiate such codings. </span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Contr.sum defaults to -1/1 coding (not 0,1).</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>TRT <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>TRT)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(data<span class="sc">$</span>TRT) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="group-mean-center-ppvt_fallk" class="level2">
<h2 class="anchored" data-anchor-id="group-mean-center-ppvt_fallk">3. Group mean center <code>PPVT_Fallk</code></h2>
<p>Q3. Insert code below to center the variable PPVT_Fallk within the clusters/classrooms</p>
<p>Answer:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#within-clustering centering</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>clu_id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>clu_id)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(clu_id) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PPVT_FallK_centered =</span> PPVT_FallK <span class="sc">-</span> <span class="fu">mean</span>(PPVT_FallK, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="visualizations" class="level2">
<h2 class="anchored" data-anchor-id="visualizations">Visualizations</h2>
<p>Q4. Create two nicely looking visualizations: One for the relationship between PPTV and EWR and one for the relationship between TRT and EWR. Make sure you plot the between-cluster (class) variability when you graph these (given how many clusters there are, randomly sample 20 of them to plot).</p>
<p>AnswerS:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fig 1</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Randomly sample 20 clusters to plot</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">500</span>) <span class="co"># for reproducibility</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>clusters_sample <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(clu_id) <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">clu_id =</span> <span class="fu">as.character</span>(clu_id)) <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">20</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(clu_id)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>data_sample <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(clu_id <span class="sc">%in%</span> clusters_sample)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_sample, <span class="fu">aes</span>(<span class="at">x =</span> PPVT_FallK, <span class="at">y =</span> ETW_SpringK, <span class="at">group =</span> clu_id)) <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">as.factor</span>(clu_id))) <span class="sc">+</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="fu">aes</span>(<span class="at">group =</span> clu_id, <span class="at">color =</span> <span class="fu">as.factor</span>(clu_id))) <span class="sc">+</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PPTV scores vs EWR scores by classroom"</span>, <span class="at">x =</span> <span class="st">"PPTV scores"</span>, <span class="at">y =</span> <span class="st">"EWR scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLM2_Ans_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fig 2</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># bubble plots</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># PPVT_FallK and ETW_SpringK</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>p1_df <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(clu_id) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_PPVT_FallK =</span> <span class="fu">mean</span>(PPVT_FallK, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_ETW_SpringK =</span> <span class="fu">mean</span>(ETW_SpringK, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_students =</span> <span class="fu">n</span>())</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">=</span> <span class="fu">ggplot</span>(p1_df, <span class="fu">aes</span>(<span class="at">x =</span> mean_PPVT_FallK, <span class="at">y =</span> mean_ETW_SpringK, <span class="at">size =</span> n_students)) <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">5</span>, <span class="at">color =</span> <span class="st">"#6096ba"</span>) <span class="sc">+</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">12</span>), <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Peabody Picture Vocabulary Test (PPVT) Scores by</span><span class="sc">\n</span><span class="st">Expressive Target Word Measure (ETW)"</span>,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Mean PPVT"</span>,</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mean ETW"</span>) <span class="sc">+</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="co"># ETW_SpringK and TVT</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>p2_df <span class="ot">=</span> data <span class="sc">%&gt;%</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(clu_id, TRT) <span class="sc">%&gt;%</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_ETW_SpringK =</span> <span class="fu">mean</span>(ETW_SpringK, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">n_students =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'clu_id'. You can override using the
`.groups` argument.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">=</span> <span class="fu">ggplot</span>(p2_df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(TRT), <span class="at">y =</span> mean_ETW_SpringK)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  ggdist<span class="sc">::</span><span class="fu">stat_halfeye</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">adjust =</span> .<span class="dv">5</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> .<span class="dv">4</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">.width =</span> <span class="dv">0</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">justification =</span> <span class="sc">-</span>.<span class="dv">9</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">point_colour =</span> <span class="cn">NA</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"#6096ba"</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="fu">factor</span>(clu_id), <span class="at">size =</span> n_students), <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">size =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Expressive Target Word Measure (ETW) Scores</span><span class="sc">\n</span><span class="st">by Condition"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Condition"</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"Treatment"</span>)) <span class="sc">+</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>combined_plot <span class="ot">=</span> p1 <span class="sc">|</span> p2</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>caption_text <span class="ot">=</span> <span class="st">"Figure 1.</span><span class="sc">\n</span><span class="st">A: Mean classroom scores on the PPVT and ETW. Each 'bubble' represents a cluster or classroom.</span><span class="sc">\n</span><span class="st">B: ETW scores by experimental condition. Each bubble represents the average ETW score for a classroom.</span><span class="sc">\n</span><span class="st">Larger bubbles represent pairs containing more students."</span></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>annotated_plot <span class="ot">=</span> combined_plot <span class="sc">&amp;</span></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_annotation</span>(</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">tag_levels =</span> <span class="st">"A"</span>,</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> caption_text,</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">theme =</span> <span class="fu">theme</span>(</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">hjust =</span> <span class="dv">0</span>)</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>annotated_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLM2_Ans_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="model-comparisons">Model comparisons</h2>
<p>Q5. Fit an unconditional means (null model), and print its summary</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>make sure you have loaded <code>lmerTest</code> to get <em>p</em>-values</p>
<p>When you load lmerTest, it modifies how summary() works on lmer models. This happens automatically, and there isn’t a specific new function you need to call.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The “model” with linear regression sets the intercept to be mean The unconditional means “null model” ends up setting the group intercepts to group means. Neither of these models have slopes.</p>
<p>Null model in lm() — lm(Y ~ 1) Null model in lmer() — lm(Y ~ 1 + (1|grouping_factor))</p>
<p>REML (Restricted Maximum Likelihood) is better for variance estimation - and that’s exactly what null models are trying to do for the data without considering any fixed effect predictor. So, choose REML in your lmer call.</p>
</div>
</div>
<p>::: Answer. ::: cell</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(ETW_SpringK <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>clu_id),</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> data)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: ETW_SpringK ~ 1 + (1 | clu_id)
   Data: data

REML criterion at convergence: 10855.9

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.8972 -0.6979 -0.2156  0.5325  3.5095 

Random effects:
 Groups   Name        Variance Std.Dev.
 clu_id   (Intercept)  19.91    4.462  
 Residual             104.43   10.219  
Number of obs: 1427, groups:  clu_id, 222

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept)  13.7248     0.4094 201.4834   33.52   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>:::</p>
<p>Q6. The intraclass correlation coefficient (ICC) measures proportion of total variance due to group membership Calculate it manually for the fitted model from the output, and print it out. Is multilevel modeling warranted here?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>A common heuristic: ICC &lt; 0.05 = Probably not needed ICC &gt; 0.05-0.1 = Multilevel warranted ICC &gt; 0.1 = Strong indication for multilevel models.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#TYPE YOUR CODE BELOW</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># a. Extract the variance components from the model output</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># b. Calculate ICC</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now use the <code>icc</code> function in easystats / performance package to calculate the icc</p>
<p>Answers:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the variance components from the model output</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>cluster_variance <span class="ot">&lt;-</span> <span class="fl">19.91</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>residual_variance <span class="ot">&lt;-</span> <span class="fl">104.43</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate ICC</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>icc <span class="ot">&lt;-</span> cluster_variance <span class="sc">/</span> (cluster_variance <span class="sc">+</span> residual_variance)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(icc, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1601</code></pre>
</div>
</div>
<p>Now use the <code>icc</code> function in easystats / performance package to calculate the icc</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#easystats</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">icc</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># Intraclass Correlation Coefficient

    Adjusted ICC: 0.160
  Unadjusted ICC: 0.160</code></pre>
</div>
</div>
<p>Is multilevel modeling warranted here? Yep! What does the ICC mean? It tells us how much variability there is between clusters. It also tells how how correlated our level 1 units are to one another. In this case, we have observe an ICC of 0.160, which indicates that 16% of the total variance in our outcome variable (students’ vocabulary knowledge scores <code>ETW_SpringK</code>) is attributable to differences between classroom (Level 2 variance).</p>
<p>Q7. Build up from the last model. Fit a model that includes all level 1 variables (no interaction)</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Type your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Tip: You’re building from the last model. So you’re building on the clustering structure. So, you’d make sure to keep the random intercept intact.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Maximum likelihood (as opposed Restricted maximum likelihood is best once you begin to have fixed effects), so set your REML flag appropriately. By default it’s True.</p>
</div>
</div>
<p>Answer:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>level_1_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(ETW_SpringK <span class="sc">~</span> TRT <span class="sc">+</span> PPVT_FallK <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>clu_id), <span class="at">data =</span> data)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(level_1_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: ETW_SpringK ~ TRT + PPVT_FallK + (1 | clu_id)
   Data: data

REML criterion at convergence: 10349.1

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.4814 -0.6259 -0.1126  0.5149  3.9787 

Random effects:
 Groups   Name        Variance Std.Dev.
 clu_id   (Intercept) 21.60    4.647   
 Residual             69.93    8.362   
Number of obs: 1427, groups:  clu_id, 222

Fixed effects:
              Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)  -25.36477    3.95423 1398.06475  -6.415 1.93e-10 ***
TRT1         -10.44860    0.45197 1250.92144 -23.118  &lt; 2e-16 ***
PPVT_FallK     0.46073    0.04665 1386.53447   9.876  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
           (Intr) TRT1  
TRT1        0.022       
PPVT_FallK -0.995 -0.020</code></pre>
</div>
</div>
<p>Q8. Fit a model that includes the fixed interaction between the level-1 variables</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note, in case you’re ever counfused about this in R formulas format Y ~ A + B + A:B (main effects + interaction term) is the same as Y ~ A*B</p>
</div>
</div>
<p>Answer:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>interaction_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(ETW_SpringK <span class="sc">~</span> TRT <span class="sc">*</span> PPVT_FallK <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>clu_id), <span class="at">data =</span> data)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(interaction_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: ETW_SpringK ~ TRT * PPVT_FallK + (1 | clu_id)
   Data: data

REML criterion at convergence: 10339.1

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.6149 -0.6202 -0.1202  0.5219  4.1549 

Random effects:
 Groups   Name        Variance Std.Dev.
 clu_id   (Intercept) 21.66    4.655   
 Residual             69.25    8.322   
Number of obs: 1427, groups:  clu_id, 222

Fixed effects:
                  Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)      -25.30463    3.93672 1396.23692  -6.428 1.77e-10 ***
TRT1              16.10042    7.33721 1244.64814   2.194   0.0284 *  
PPVT_FallK         0.46021    0.04644 1384.47854   9.909  &lt; 2e-16 ***
TRT1:PPVT_FallK   -0.31512    0.08693 1245.16529  -3.625   0.0003 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) TRT1   PPVT_F
TRT1         0.005              
PPVT_FallK  -0.995 -0.004       
TRT1:PPVT_F -0.004 -0.998  0.002</code></pre>
</div>
</div>
<p>Q9. Compare the main effects and interaction models. Which model is the best? Try the likelihood ratio test, AIC and BIC, and jot down your thoughts.</p>
<p>Answer:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">test_likelihoodratio</span>(level_1_model, interaction_model, <span class="at">REML=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model3 are not supported models and have been dropped.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)

Name   |           Model | df | df_diff |  Chi2 |      p
--------------------------------------------------------
model1 | lmerModLmerTest |  5 |         |       |       
model2 | lmerModLmerTest |  6 |       1 | 13.11 | &lt; .001</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>AIC and BIC can be used with the models you’ve already fitted.</p>
<p>However, for likelihood ratio tests of nested models, Maximum likelihood (as opposed Restricted maximum likelihood) is best for model comparison. So such a likelihood ratio test will require models to be re-fit with REML=TRUE, just to give better model comparison results. )</p>
</div>
</div>
<p>Answer: - The interaction model is statistically superior to the main effects model, as indicated by lower AIC and BIC scores. This is further confirmed by a statistically significant likelihood ratio test (<span class="math inline">\(\chi^2 = 8.39, p = .0038\)</span>). This suggests that including the interaction between <code>TRT</code> and <code>PPVT_FallK</code> provides a better fit to the data.</p>
<p>Q10. Use the best model from above and fit a model that adds random slopes for <code>TRT</code></p>
<p>Answer:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>best_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(ETW_SpringK <span class="sc">~</span> TRT <span class="sc">*</span> PPVT_FallK <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span> TRT<span class="sc">|</span>clu_id), <span class="at">data =</span> data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Next, let’s create a model with a random slope for treatment and PPVT scores. This will be our maximal model.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>We could include a random slope for the interaction between the two, but we only have 6 students per classroom and makes our model too complex.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>complex_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(ETW_SpringK <span class="sc">~</span> TRT <span class="sc">*</span> PPVT_FallK <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> TRT <span class="sc">+</span> PPVT_FallK<span class="sc">|</span>clu_id), <span class="at">data =</span> data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, :
Model failed to converge with max|grad| = 1.70299 (tol = 0.002, component 1)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, : Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?;Model is nearly unidentifiable: large eigenvalue ratio
 - Rescale variables?</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">isSingular</span>(complex_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>Take a look at the maximal model output. What is the warning message? We observe that the more complex model has a singular fit, which likely results from overfitting the data. In particular, the more complex model contains random slopes for both <code>TRT</code> and <code>PPVT_FallK</code> within clusters (<code>clu_id</code>). We can infer that there is not enough variation in <code>TRT</code> or <code>PPVT_FallK</code> within clusters, so the model may not be able to estimate random effects reliably. To get rid of this warning, we could reduce complexity in the model by removing some of the random slopes.</p>
</section>
<section id="model-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="model-interpretation">Model interpretation</h2>
<p>Through model comparisons like before, we can tell that the model with random slopes for TRT and random intercepts for classroom is the best. Now let’s use this best model and examine the fixed effects.</p>
<p>Q 11. Please interpret these effects/coefs in a sentence or two.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the best model and output a nice summary table of results.</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex) <span class="co"># load afex in</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">mixed</span>(ETW_SpringK <span class="sc">~</span> TRT <span class="sc">*</span> PPVT_FallK <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span> TRT<span class="sc">|</span>clu_id), <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Contrasts set to contr.sum for the following variables: TRT, clu_id</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Numerical variables NOT centered on 0: PPVT_FallK
If in interactions, interpretation of lower order (e.g., main) effects difficult.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nice</span>(m) <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Effect</th>
<th style="text-align: left;">df</th>
<th style="text-align: left;">F</th>
<th style="text-align: left;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">TRT</td>
<td style="text-align: left;">1, 1248.94</td>
<td style="text-align: left;">3.15 +</td>
<td style="text-align: left;">.076</td>
</tr>
<tr class="even">
<td style="text-align: left;">PPVT_FallK</td>
<td style="text-align: left;">1, 1247.01</td>
<td style="text-align: left;">112.04 ***</td>
<td style="text-align: left;">&lt;.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TRT:PPVT_FallK</td>
<td style="text-align: left;">1, 1244.19</td>
<td style="text-align: left;">10.76 **</td>
<td style="text-align: left;">.001</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emtrends</span>(best_model, <span class="sc">~</span>TRT, <span class="at">var=</span><span class="st">"PPVT_FallK"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">test</span>() <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">TRT</th>
<th style="text-align: right;">PPVT_FallK.trend</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">t.ratio</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">-0.5</td>
<td style="text-align: right;">0.3120067</td>
<td style="text-align: right;">0.0565135</td>
<td style="text-align: right;">1180.010</td>
<td style="text-align: right;">5.520926</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.5</td>
<td style="text-align: right;">0.5827390</td>
<td style="text-align: right;">0.0617509</td>
<td style="text-align: right;">1167.729</td>
<td style="text-align: right;">9.436926</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Let’s evaluate the variance components of the model.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(best_model, <span class="at">effects=</span><span class="st">"random"</span>) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 28%">
<col style="width: 16%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Coefficient</th>
<th style="text-align: left;">SE</th>
<th style="text-align: right;">CI</th>
<th style="text-align: left;">CI_low</th>
<th style="text-align: left;">CI_high</th>
<th style="text-align: left;">Effects</th>
<th style="text-align: left;">Group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SD (Intercept)</td>
<td style="text-align: right;">4.7798625</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">random</td>
<td style="text-align: left;">clu_id</td>
</tr>
<tr class="even">
<td style="text-align: left;">SD (TRT1)</td>
<td style="text-align: right;">6.6910483</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">random</td>
<td style="text-align: left;">clu_id</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cor (Intercept~TRT1)</td>
<td style="text-align: right;">-0.8922365</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">random</td>
<td style="text-align: left;">clu_id</td>
</tr>
<tr class="even">
<td style="text-align: left;">SD (Observations)</td>
<td style="text-align: right;">7.5474782</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">random</td>
<td style="text-align: left;">Residual</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Q12. How do you interpet the modeling results, in terms of varaince in intercept, treatment effect, and residuals?</p>
<p>Answers: - The variance is 25.01 for the intercepts across the different classrooms (<code>clu_id</code>). This suggests there is substantial variability in the baseline <code>ETW_SpringK</code> scores that can be attributed to differences between classrooms before considering <code>TRT</code> or <code>PPVT_FallK</code> scores.</p>
<ul>
<li><p>The variance associated with the treatment effect (<code>TRT</code>) across classrooms is 45.51. This suggests significant variability in how the treatment effect on <code>ETW_SpringK</code> scores differs from one classroom to another.</p></li>
<li><p>The variance of residuals is 57.02. This indicates the remaining within-classroom variance in student scores that cannot be explained by the model’s fixed effects or the classroom-level random effects.</p></li>
<li><p>Overall, our variance components are significant for both the random intercept and slope for <code>TRT</code>. This suggests that multilevel modeling is, indeed, appropriate and necessary to account for the clustering of student scores within classrooms and the variability in treatment effects across classrooms.</p></li>
</ul>
</section>
<section id="model-fit" class="level2">
<h2 class="anchored" data-anchor-id="model-fit">Model fit</h2>
<p>We can then calculate the conditional and marginal pseudo-<span class="math inline">\(R^2\)</span> of the model</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r2</span>(best_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># R2 for Mixed Models

  Conditional R2: 0.543
     Marginal R2: 0.262</code></pre>
</div>
</div>
<p>The semi-<span class="math inline">\(R^2\)</span> for the <code>PPVT</code> variable is calculated using the <code>partR2</code> function from <code>partR2</code> package</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(partR2)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">partR2</span>(best_model, <span class="at">data =</span> data, <span class="at">partvars =</span> <span class="fu">c</span>(<span class="st">"PPVT_FallK"</span>), <span class="at">R2_type =</span> <span class="st">"marginal"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>

R2 (marginal) and 95% CI for the full model: 
 R2     CI_lower CI_upper nboot ndf
 0.2619 NA       NA       1     4  

----------

Part (semi-partial) R2:
 Predictor(s) R2     CI_lower CI_upper nboot ndf
 Model        0.2619 NA       NA       1     4  
 PPVT_FallK   0.0000 NA       NA       1     4  </code></pre>
</div>
</div>
<p>We can visualize the random intercepts and slopes in your model</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>random <span class="ot">&lt;-</span> <span class="fu">estimate_grouplevel</span>(best_model)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(random) <span class="sc">+</span> <span class="fu">theme_lucid</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLM2_Ans_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<p>Q12. Check model assumptions with <code>check_model</code>. Do any of the assumptions appear to be violated?</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(best_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLM2_Ans_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Answer:</p>
<p>We can also visualize the interaction between <code>TRT</code> and <code>PPVT</code> score on ETW (I would check out the <code>interactions</code> or <code>ggeffects</code> packages. They have some nice features for plotting interactions.)</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(best_model, <span class="at">pred =</span> <span class="st">"PPVT_FallK"</span>, <span class="at">modx =</span> <span class="st">"TRT"</span>, <span class="at">data =</span> data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="MLM2_Ans_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="reporting-results" class="level2">
<h2 class="anchored" data-anchor-id="reporting-results">Reporting Results</h2>
<p>Q14. Briefly highlight what you think needs to be present in the results. I will share what a complete report would like in the solution.</p>
<p>Write-up the results of your MLM model incorporating the above information. This write-up should resemble what you would find in a published paper. You can use the textbook for guidance and the <code>report</code> function from <code>easystats</code></p>
<p>The present study investigated the impact of a vocabulary instruction intervention on students’ knowledge, using a nested data structure with two levels: students (Level 1) nested within classrooms (Level 2). The analysis included 1,427 students distributed across 222 classrooms. Classrooms varied in size, with an average of approximately 6.4 students per classroom (<span class="math inline">\(SD = 2.2, range = [2, 18]\)</span>).</p>
<p>The relationship between the intervention and vocabulary knowledge was modeled using a multilevel linear model, represented by the following equation:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>equatiomatic<span class="sc">::</span><span class="fu">extract_eq</span>(best_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><span class="math display">\[
\begin{aligned}
  \operatorname{ETW\_SpringK}_{i}  &amp;\sim N \left(\mu, \sigma^2 \right) \\
    \mu &amp;=\alpha_{j[i]} + \beta_{1j[i]}(\operatorname{TRT}_{\operatorname{1}}) + \beta_{2}(\operatorname{PPVT\_FallK}) + \beta_{3}(\operatorname{PPVT\_FallK} \times \operatorname{TRT}_{\operatorname{1}}) \\    
\left(
  \begin{array}{c}
    \begin{aligned}
      &amp;\alpha_{j} \\
      &amp;\beta_{1j}
    \end{aligned}
  \end{array}
\right)
  &amp;\sim N \left(
\left(
  \begin{array}{c}
    \begin{aligned}
      &amp;\mu_{\alpha_{j}} \\
      &amp;\mu_{\beta_{1j}}
    \end{aligned}
  \end{array}
\right)
,
\left(
  \begin{array}{cc}
     \sigma^2_{\alpha_{j}} &amp; \rho_{\alpha_{j}\beta_{1j}} \\
     \rho_{\beta_{1j}\alpha_{j}} &amp; \sigma^2_{\beta_{1j}}
  \end{array}
\right)
\right)
    \text{, for clu\_id j = 1,} \dots \text{,J}
\end{aligned}
\]</span></p>
</div>
</div>
<p>where <span class="math inline">\(ETW\_SpringK\)</span> is the student’s score on the vocabulary knowledge assessment, <span class="math inline">\(TRT\)</span> is the treatment condition, <span class="math inline">\(PPVT\_FallK\)</span> is the Peabody Picture Vocabulary Test score, and <span class="math inline">\((1 + TRT|clu\_id)\)</span> represents the random intercepts and slopes for treatment across classrooms. Note that <span class="math inline">\(ETW\_SpringK\)</span>, <span class="math inline">\(TRT\)</span>, and <span class="math inline">\(PPVT\_FallK\)</span> are all Level 1 variables, and <span class="math inline">\(clu\_id\)</span> is at Level 2. For the above analysis, we mean centered <span class="math inline">\(PPVT\_FallK\)</span> within each cluster and deviation coded <span class="math inline">\(TRT\)</span>.</p>
<p>Before settling on the above model, we estimated an unconditional means (null) model and maximal model, which included a random slope for both treatment and PPVT scores. We compared the above model (<span class="math inline">\(df = 8\)</span>) to the maximal model (<span class="math inline">\(df = 11\)</span>) using a likelihood ratio test from the easystats package (version 0.6.0). We found that the more complex model did not significantly improve model fit (<span class="math inline">\(\chi^2 = 4.85, p = 0.185\)</span>). We therefore proceeded to use the simpler model for our analyses, as there was not sufficient evidence to justify additional complexity in our model.</p>
<p>We checked our model assumptions (linearity, normality of residuals, homoscedasticity, collinearity) visually, using diagnostic plots from the performance package (version 0.10.5). Based on this visual assessment, we found that all our model assumptions were satisfied. The Intraclass Correlation Coefficient (ICC) for the outcome variable was calculated as 0.16, suggesting that 16% of the variance in vocabulary knowledge scores could be attributed to differences between classrooms. The models were estimated using Restricted Maximum Likelihood (REML) to account for the nested data structure. The lme4 package (version 1.1.34) was used for fitting the model, with the interactions package (version 1.1.5) for estimating and plotting interactions.</p>
<p>The fixed effects analysis revealed a significant intercept (<span class="math inline">\(b = 13.47, SE = 0.40, t(209) = 34.03, p &lt; .001\)</span>), indicating a high baseline level of vocabulary knowledge. The treatment effect was also significant (<span class="math inline">\(b = 10.47, SE = 0.62, t(213) = 17.02, p &lt; .001\)</span>), suggesting that the treatment had a substantial positive impact on vocabulary knowledge. Additionally, PPVT scores were positively associated with ETW scores (<span class="math inline">\(b = 0.43, SE = 0.04, t(1091) = 9.67, p &lt; .001\)</span>), indicating that higher initial vocabulary levels were associated with higher post-intervention vocabulary knowledge. The interaction between treatment and PPVT scores was also significant (<span class="math inline">\(b = 0.28, SE = 0.09, t(1074) = 3.06, p = .002\)</span>), suggesting that the treatment effect varied as a function of initial vocabulary levels.</p>
<p>Regarding random effects, we observe a variance of 25.01 (<span class="math inline">\(SD = 5.00\)</span>) for the intercepts across the different classrooms. This suggests there is substantial variability in the baseline ETW scores that can be attributed to differences between classrooms before considering treatment or PPVT scores. The variance associated with the treatment effect (<span class="math inline">\(SD = 6.75\)</span>). This suggests significant variability in how the treatment effect on ETW scores differs from across clasrooms. Finally, the variance of residuals was 57.02 (<span class="math inline">\(SD = 7.55\)</span>), indicating within-classroom variance in student scores that cannot be explained by the model’s fixed effects or the classroom-level random effects. Overall, our variance components are significant for both the random intercept and slope for treatment. This suggests that multilevel modeling is, indeed, appropriate and necessary to account for the clustering of student scores within classrooms and the variability in treatment effects across classrooms.</p>
<p>the model estimated the standard deviation of the random intercepts for classrooms (<span class="math inline">\(SD = 5.00\)</span>), indicating variability in baseline ETW scores across classrooms. The correlation between the random intercepts and slopes for treatment within classrooms was estimated to be 0.89, suggesting a strong positive relationship between the classroom baseline scores and the treatment effect. The standard deviation of the random slopes for treatment (<span class="math inline">\(SD = 6.75\)</span>) indicated substantial variability in the treatment effect across classrooms. The residual standard deviation (<span class="math inline">\(SD = 7.55\)</span>) reflected the within-classroom variability in ETW scores that was not explained by the model’s fixed and random effects.</p>
<p>Taken together, these results suggest that both the treatment and initial PPVT scores are significant predictors of students’ vocabulary knowledge. There was a notable interaction effect, suggesting that the benefit of the treatment varies depending on students’ initial vocabulary levels. The significant random effects for treatment across classrooms underscore the intervention’s differential effectiveness depending on classroom context. These findings highlight the importance of considering both the individual and contextual factors in educational interventions. ```</p>
<!-- -->

</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb58" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "MLM2 - Ans"</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Advanced Statistics in Psychology"</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> </span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: cosmo</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a><span class="an">editor:</span><span class="co"> </span></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a><span class="co">  markdown: </span></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a><span class="co">    wrap: 72</span></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a><span class="fu"># Lab 1: MLM</span></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>Today's lab uses data from a study conducted by Coyne et al. (2019),</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>which examined the impact of a high-quality, evidence-based vocabulary</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>instruction intervention in kindergarten. The data consists of **1,428</span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>students** who were **nested in 233 clusters** or classrooms (<span class="in">`clu_id`</span>).</span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>In the sample of at-risk youth in the classroom (N = 6), half were</span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>allocated to **treatment** and the other half to **control**. The</span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>treatment group received supplemental small-group vocabulary instruction</span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a>in addition to the whole-group instruction, while the control group</span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a>received only whole-group vocabulary instruction. Since the observations</span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a>were not independent (due to students being nested within classrooms),</span>
<span id="cb58-28"><a href="#cb58-28" aria-hidden="true" tabindex="-1"></a>the researchers needed to account for this in their analysis.</span>
<span id="cb58-29"><a href="#cb58-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-30"><a href="#cb58-30" aria-hidden="true" tabindex="-1"></a>***The main question that the researchers aimed to answer was whether</span>
<span id="cb58-31"><a href="#cb58-31" aria-hidden="true" tabindex="-1"></a>the supplemental small-group kindergarten vocabulary instruction</span>
<span id="cb58-32"><a href="#cb58-32" aria-hidden="true" tabindex="-1"></a>intervention increased students' knowledge of the vocabulary words</span>
<span id="cb58-33"><a href="#cb58-33" aria-hidden="true" tabindex="-1"></a>taught in the intervention.*** To measure vocabulary knowledge, the</span>
<span id="cb58-34"><a href="#cb58-34" aria-hidden="true" tabindex="-1"></a>researchers used an ETW (<span class="in">`ETW_SpringK`</span>) assessment, which evaluated</span>
<span id="cb58-35"><a href="#cb58-35" aria-hidden="true" tabindex="-1"></a>students' ability to explain the meaning of a given word. The assessment</span>
<span id="cb58-36"><a href="#cb58-36" aria-hidden="true" tabindex="-1"></a>was administered after the intervention concluded, in the spring of</span>
<span id="cb58-37"><a href="#cb58-37" aria-hidden="true" tabindex="-1"></a>kindergarten. In the sample, ETW scores ranged from 0 to 52 (the maximum</span>
<span id="cb58-38"><a href="#cb58-38" aria-hidden="true" tabindex="-1"></a>score), with a mean of 13.65 and a standard deviation of 11.10. To</span>
<span id="cb58-39"><a href="#cb58-39" aria-hidden="true" tabindex="-1"></a>answer the research question, the researchers used two fixed effects and</span>
<span id="cb58-40"><a href="#cb58-40" aria-hidden="true" tabindex="-1"></a>their interaction: TRT (1 = treatment and 0 = control) and PPVT (Peabody</span>
<span id="cb58-41"><a href="#cb58-41" aria-hidden="true" tabindex="-1"></a>Picture Vocabulary Test, which measures students' vocabulary before the</span>
<span id="cb58-42"><a href="#cb58-42" aria-hidden="true" tabindex="-1"></a>intervention; <span class="in">`PPVT_FallK`</span>).</span>
<span id="cb58-43"><a href="#cb58-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-44"><a href="#cb58-44" aria-hidden="true" tabindex="-1"></a>*Coyne, M. D., McCoach, D. B., Ware, S., Austin, C. R., Loftus-Rattan,</span>
<span id="cb58-45"><a href="#cb58-45" aria-hidden="true" tabindex="-1"></a>S. M., &amp; Baker, D. L. (2019). Racing Against the Vocabulary Gap: Matthew</span>
<span id="cb58-46"><a href="#cb58-46" aria-hidden="true" tabindex="-1"></a>Effects in Early Vocabulary Instruction and Intervention. Exceptional</span>
<span id="cb58-47"><a href="#cb58-47" aria-hidden="true" tabindex="-1"></a>Children*, 85(2), 163–179. <span class="ot">&lt;https://doi.org/10.1177/0014402918789162&gt;</span></span>
<span id="cb58-48"><a href="#cb58-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-49"><a href="#cb58-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## Load packages</span></span>
<span id="cb58-50"><a href="#cb58-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-51"><a href="#cb58-51" aria-hidden="true" tabindex="-1"></a><span class="in">```{r message=FALSE, warning=FALSE}</span></span>
<span id="cb58-52"><a href="#cb58-52" aria-hidden="true" tabindex="-1"></a><span class="in"># fill in packages you need as you go here</span></span>
<span id="cb58-53"><a href="#cb58-53" aria-hidden="true" tabindex="-1"></a><span class="in">library(tidyverse) # data wrangling</span></span>
<span id="cb58-54"><a href="#cb58-54" aria-hidden="true" tabindex="-1"></a><span class="in">library(knitr) # nice tables</span></span>
<span id="cb58-55"><a href="#cb58-55" aria-hidden="true" tabindex="-1"></a><span class="in">library(patchwork) # combine figures</span></span>
<span id="cb58-56"><a href="#cb58-56" aria-hidden="true" tabindex="-1"></a><span class="in">library(lme4) # fit mixed models</span></span>
<span id="cb58-57"><a href="#cb58-57" aria-hidden="true" tabindex="-1"></a><span class="in">library(lmerTest) # mixed models</span></span>
<span id="cb58-58"><a href="#cb58-58" aria-hidden="true" tabindex="-1"></a><span class="in">library(broom.mixed) # tidy output of mixed models</span></span>
<span id="cb58-59"><a href="#cb58-59" aria-hidden="true" tabindex="-1"></a><span class="in">library(afex) # fit mixed models for lrt test</span></span>
<span id="cb58-60"><a href="#cb58-60" aria-hidden="true" tabindex="-1"></a><span class="in">library(emmeans) # marginal means</span></span>
<span id="cb58-61"><a href="#cb58-61" aria-hidden="true" tabindex="-1"></a><span class="in">library(ggeffects) # marginal means</span></span>
<span id="cb58-62"><a href="#cb58-62" aria-hidden="true" tabindex="-1"></a><span class="in">library(ggrain) # rain plots</span></span>
<span id="cb58-63"><a href="#cb58-63" aria-hidden="true" tabindex="-1"></a><span class="in">library(easystats) # nice ecosystem of packages</span></span>
<span id="cb58-64"><a href="#cb58-64" aria-hidden="true" tabindex="-1"></a><span class="in">library(interactions)</span></span>
<span id="cb58-65"><a href="#cb58-65" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-66"><a href="#cb58-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-67"><a href="#cb58-67" aria-hidden="true" tabindex="-1"></a><span class="fu">## Load data</span></span>
<span id="cb58-68"><a href="#cb58-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-71"><a href="#cb58-71" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-72"><a href="#cb58-72" aria-hidden="true" tabindex="-1"></a><span class="co"># read in data file</span></span>
<span id="cb58-73"><a href="#cb58-73" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Ch3_MLM_R.csv"</span>)</span>
<span id="cb58-74"><a href="#cb58-74" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-75"><a href="#cb58-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-76"><a href="#cb58-76" aria-hidden="true" tabindex="-1"></a><span class="fu"># Lab 1</span></span>
<span id="cb58-77"><a href="#cb58-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-78"><a href="#cb58-78" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data structure</span></span>
<span id="cb58-79"><a href="#cb58-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-80"><a href="#cb58-80" aria-hidden="true" tabindex="-1"></a>Q1. What are the Level 1 and Level 2 variables in this study? How many</span>
<span id="cb58-81"><a href="#cb58-81" aria-hidden="true" tabindex="-1"></a>units are in Level 1? Level 2? Are the fixed effects at Level 1 or Level</span>
<span id="cb58-82"><a href="#cb58-82" aria-hidden="true" tabindex="-1"></a>2?</span>
<span id="cb58-83"><a href="#cb58-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-84"><a href="#cb58-84" aria-hidden="true" tabindex="-1"></a>Q2. What are the Level 1 and Level 2 variables in this study? How many</span>
<span id="cb58-85"><a href="#cb58-85" aria-hidden="true" tabindex="-1"></a>units are in Level 1? Level 2? Are the fixed effects at Level 1 or Level</span>
<span id="cb58-86"><a href="#cb58-86" aria-hidden="true" tabindex="-1"></a>2?</span>
<span id="cb58-87"><a href="#cb58-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-88"><a href="#cb58-88" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">**Answers:**</span><span class="co">]</span>{.underline}</span>
<span id="cb58-89"><a href="#cb58-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-90"><a href="#cb58-90" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>[**Level 1 variables: <span class="in">`ETW_SpringK`</span>, <span class="in">`TRT`</span>, and</span>
<span id="cb58-91"><a href="#cb58-91" aria-hidden="true" tabindex="-1"></a>    <span class="in">`PPVT_FallK`</span>.**]{.underline}</span>
<span id="cb58-92"><a href="#cb58-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-93"><a href="#cb58-93" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>[**There are 1,427 units in Level 1. There are 222 units in Level</span>
<span id="cb58-94"><a href="#cb58-94" aria-hidden="true" tabindex="-1"></a>    2.**]{.underline}</span>
<span id="cb58-95"><a href="#cb58-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-96"><a href="#cb58-96" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>[**The fixed effects are at Level 1 because they pertain to the</span>
<span id="cb58-97"><a href="#cb58-97" aria-hidden="true" tabindex="-1"></a>    individual student-level variables and their</span>
<span id="cb58-98"><a href="#cb58-98" aria-hidden="true" tabindex="-1"></a>    interactions.**]{.underline}</span>
<span id="cb58-99"><a href="#cb58-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-102"><a href="#cb58-102" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-103"><a href="#cb58-103" aria-hidden="true" tabindex="-1"></a><span class="co"># Computing Dataset Statistics:</span></span>
<span id="cb58-104"><a href="#cb58-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-105"><a href="#cb58-105" aria-hidden="true" tabindex="-1"></a><span class="co"># assuming 'data' is the dataframe and 'clu_id' identifies the clusters/classrooms</span></span>
<span id="cb58-106"><a href="#cb58-106" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb58-107"><a href="#cb58-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(clu_id) <span class="sc">%&gt;%</span></span>
<span id="cb58-108"><a href="#cb58-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">N_students =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb58-109"><a href="#cb58-109" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb58-110"><a href="#cb58-110" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb58-111"><a href="#cb58-111" aria-hidden="true" tabindex="-1"></a>    <span class="at">N_clusters =</span> <span class="fu">n</span>(),</span>
<span id="cb58-112"><a href="#cb58-112" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_students =</span> <span class="fu">sum</span>(N_students),</span>
<span id="cb58-113"><a href="#cb58-113" aria-hidden="true" tabindex="-1"></a>    <span class="at">Average_students_per_classroom =</span> <span class="fu">mean</span>(N_students),</span>
<span id="cb58-114"><a href="#cb58-114" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD_students_per_classroom =</span> <span class="fu">sd</span>(N_students),</span>
<span id="cb58-115"><a href="#cb58-115" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min_students_in_classroom =</span> <span class="fu">min</span>(N_students),</span>
<span id="cb58-116"><a href="#cb58-116" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max_students_in_classroom =</span> <span class="fu">max</span>(N_students)</span>
<span id="cb58-117"><a href="#cb58-117" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb58-118"><a href="#cb58-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-119"><a href="#cb58-119" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the values to variables for easier printing</span></span>
<span id="cb58-120"><a href="#cb58-120" aria-hidden="true" tabindex="-1"></a>n_clusters <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>N_clusters</span>
<span id="cb58-121"><a href="#cb58-121" aria-hidden="true" tabindex="-1"></a>total_students <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>Total_students</span>
<span id="cb58-122"><a href="#cb58-122" aria-hidden="true" tabindex="-1"></a>average_students <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>Average_students_per_classroom</span>
<span id="cb58-123"><a href="#cb58-123" aria-hidden="true" tabindex="-1"></a>sd_students <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>SD_students_per_classroom</span>
<span id="cb58-124"><a href="#cb58-124" aria-hidden="true" tabindex="-1"></a>min_students <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>Min_students_in_classroom</span>
<span id="cb58-125"><a href="#cb58-125" aria-hidden="true" tabindex="-1"></a>max_students <span class="ot">&lt;-</span> summary_stats<span class="sc">$</span>Max_students_in_classroom</span>
<span id="cb58-126"><a href="#cb58-126" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-127"><a href="#cb58-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-130"><a href="#cb58-130" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-131"><a href="#cb58-131" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Number of clusters (classrooms):"</span>, n_clusters, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb58-132"><a href="#cb58-132" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-133"><a href="#cb58-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-136"><a href="#cb58-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-137"><a href="#cb58-137" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Total number of students:"</span>, total_students, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb58-138"><a href="#cb58-138" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-139"><a href="#cb58-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-142"><a href="#cb58-142" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-143"><a href="#cb58-143" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Average number of students per classroom:"</span>, <span class="fu">round</span>(average_students, <span class="dv">1</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb58-144"><a href="#cb58-144" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-145"><a href="#cb58-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-148"><a href="#cb58-148" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-149"><a href="#cb58-149" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Standard deviation of students per classroom:"</span>, <span class="fu">round</span>(sd_students, <span class="dv">1</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb58-150"><a href="#cb58-150" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-151"><a href="#cb58-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-154"><a href="#cb58-154" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-155"><a href="#cb58-155" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Minimum number of students in a classroom:"</span>, min_students, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb58-156"><a href="#cb58-156" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-157"><a href="#cb58-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-160"><a href="#cb58-160" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-161"><a href="#cb58-161" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Maximum number of students in a classroom:"</span>, max_students, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb58-162"><a href="#cb58-162" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-163"><a href="#cb58-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-164"><a href="#cb58-164" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. Deviation code (0.5, -0.5), aka effect code for the treatment variable</span></span>
<span id="cb58-165"><a href="#cb58-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-166"><a href="#cb58-166" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb58-167"><a href="#cb58-167" aria-hidden="true" tabindex="-1"></a>**NOTE**: Deviation/Effect coding is one way to recode categorical</span>
<span id="cb58-168"><a href="#cb58-168" aria-hidden="true" tabindex="-1"></a>variables for regression analysis. They transform the treatment variable</span>
<span id="cb58-169"><a href="#cb58-169" aria-hidden="true" tabindex="-1"></a>(TRT) from: treatment → 0.5 control → -0.5</span>
<span id="cb58-170"><a href="#cb58-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-171"><a href="#cb58-171" aria-hidden="true" tabindex="-1"></a>Remember that different ways of coding categorical variables do not</span>
<span id="cb58-172"><a href="#cb58-172" aria-hidden="true" tabindex="-1"></a>actually influence the results/ predictions. But they can influence how</span>
<span id="cb58-173"><a href="#cb58-173" aria-hidden="true" tabindex="-1"></a>we interpret coefficients.</span>
<span id="cb58-174"><a href="#cb58-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-175"><a href="#cb58-175" aria-hidden="true" tabindex="-1"></a>Now, with deviation coding (-0.5,0.5), here: Intercept = grand mean</span>
<span id="cb58-176"><a href="#cb58-176" aria-hidden="true" tabindex="-1"></a>across all groups Treatment coefficient = difference between groups</span>
<span id="cb58-177"><a href="#cb58-177" aria-hidden="true" tabindex="-1"></a>(divided by 2)</span>
<span id="cb58-178"><a href="#cb58-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-179"><a href="#cb58-179" aria-hidden="true" tabindex="-1"></a>With dummy coding (0/1), it'd be: Intercept = mean of reference group</span>
<span id="cb58-180"><a href="#cb58-180" aria-hidden="true" tabindex="-1"></a>Treatment coefficient = difference from reference group</span>
<span id="cb58-181"><a href="#cb58-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-182"><a href="#cb58-182" aria-hidden="true" tabindex="-1"></a>The key advantage? When interpreting interactions, deviation coding</span>
<span id="cb58-183"><a href="#cb58-183" aria-hidden="true" tabindex="-1"></a>makes results more intuitive since coefficients show deviations from</span>
<span id="cb58-184"><a href="#cb58-184" aria-hidden="true" tabindex="-1"></a>overall means (or overall main effect) rather than from a reference</span>
<span id="cb58-185"><a href="#cb58-185" aria-hidden="true" tabindex="-1"></a>group (which may not always be clear or relevant, making interpretation</span>
<span id="cb58-186"><a href="#cb58-186" aria-hidden="true" tabindex="-1"></a>harder) .</span>
<span id="cb58-187"><a href="#cb58-187" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb58-188"><a href="#cb58-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-191"><a href="#cb58-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-192"><a href="#cb58-192" aria-hidden="true" tabindex="-1"></a><span class="co">#deviation code the TRT var</span></span>
<span id="cb58-193"><a href="#cb58-193" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb58-194"><a href="#cb58-194" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TRT =</span> <span class="fu">ifelse</span>(TRT <span class="sc">==</span> <span class="dv">1</span>, <span class="fl">0.5</span>, <span class="sc">-</span><span class="fl">0.5</span>))</span>
<span id="cb58-195"><a href="#cb58-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-196"><a href="#cb58-196" aria-hidden="true" tabindex="-1"></a><span class="co"># Note, one can also use contr.sum to instantiate such codings. </span></span>
<span id="cb58-197"><a href="#cb58-197" aria-hidden="true" tabindex="-1"></a><span class="co"># Contr.sum defaults to -1/1 coding (not 0,1).</span></span>
<span id="cb58-198"><a href="#cb58-198" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>TRT <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>TRT)</span>
<span id="cb58-199"><a href="#cb58-199" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(data<span class="sc">$</span>TRT) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb58-200"><a href="#cb58-200" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-201"><a href="#cb58-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-202"><a href="#cb58-202" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Group mean center `PPVT_Fallk`</span></span>
<span id="cb58-203"><a href="#cb58-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-204"><a href="#cb58-204" aria-hidden="true" tabindex="-1"></a>Q3. Insert code below to center the variable PPVT_Fallk within the</span>
<span id="cb58-205"><a href="#cb58-205" aria-hidden="true" tabindex="-1"></a>clusters/classrooms</span>
<span id="cb58-206"><a href="#cb58-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-207"><a href="#cb58-207" aria-hidden="true" tabindex="-1"></a>Answer:</span>
<span id="cb58-208"><a href="#cb58-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-211"><a href="#cb58-211" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-212"><a href="#cb58-212" aria-hidden="true" tabindex="-1"></a><span class="co">#within-clustering centering</span></span>
<span id="cb58-213"><a href="#cb58-213" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>clu_id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>clu_id)</span>
<span id="cb58-214"><a href="#cb58-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-215"><a href="#cb58-215" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb58-216"><a href="#cb58-216" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(clu_id) <span class="sc">%&gt;%</span></span>
<span id="cb58-217"><a href="#cb58-217" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PPVT_FallK_centered =</span> PPVT_FallK <span class="sc">-</span> <span class="fu">mean</span>(PPVT_FallK, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb58-218"><a href="#cb58-218" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb58-219"><a href="#cb58-219" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-220"><a href="#cb58-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-221"><a href="#cb58-221" aria-hidden="true" tabindex="-1"></a><span class="fu">## Visualizations</span></span>
<span id="cb58-222"><a href="#cb58-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-223"><a href="#cb58-223" aria-hidden="true" tabindex="-1"></a>Q4. Create two nicely looking visualizations: One for the relationship</span>
<span id="cb58-224"><a href="#cb58-224" aria-hidden="true" tabindex="-1"></a>between PPTV and EWR and one for the relationship between TRT and EWR.</span>
<span id="cb58-225"><a href="#cb58-225" aria-hidden="true" tabindex="-1"></a>Make sure you plot the between-cluster (class) variability when you</span>
<span id="cb58-226"><a href="#cb58-226" aria-hidden="true" tabindex="-1"></a>graph these (given how many clusters there are, randomly sample 20 of</span>
<span id="cb58-227"><a href="#cb58-227" aria-hidden="true" tabindex="-1"></a>them to plot).</span>
<span id="cb58-228"><a href="#cb58-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-229"><a href="#cb58-229" aria-hidden="true" tabindex="-1"></a>AnswerS:</span>
<span id="cb58-230"><a href="#cb58-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-233"><a href="#cb58-233" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-234"><a href="#cb58-234" aria-hidden="true" tabindex="-1"></a><span class="co"># fig 1</span></span>
<span id="cb58-235"><a href="#cb58-235" aria-hidden="true" tabindex="-1"></a><span class="co"># Randomly sample 20 clusters to plot</span></span>
<span id="cb58-236"><a href="#cb58-236" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">500</span>) <span class="co"># for reproducibility</span></span>
<span id="cb58-237"><a href="#cb58-237" aria-hidden="true" tabindex="-1"></a>clusters_sample <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb58-238"><a href="#cb58-238" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(clu_id) <span class="sc">%&gt;%</span></span>
<span id="cb58-239"><a href="#cb58-239" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">clu_id =</span> <span class="fu">as.character</span>(clu_id)) <span class="sc">%&gt;%</span></span>
<span id="cb58-240"><a href="#cb58-240" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">20</span>) <span class="sc">%&gt;%</span></span>
<span id="cb58-241"><a href="#cb58-241" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(clu_id)</span>
<span id="cb58-242"><a href="#cb58-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-243"><a href="#cb58-243" aria-hidden="true" tabindex="-1"></a>data_sample <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb58-244"><a href="#cb58-244" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(clu_id <span class="sc">%in%</span> clusters_sample)</span>
<span id="cb58-245"><a href="#cb58-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-246"><a href="#cb58-246" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_sample, <span class="fu">aes</span>(<span class="at">x =</span> PPVT_FallK, <span class="at">y =</span> ETW_SpringK, <span class="at">group =</span> clu_id)) <span class="sc">+</span></span>
<span id="cb58-247"><a href="#cb58-247" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">as.factor</span>(clu_id))) <span class="sc">+</span></span>
<span id="cb58-248"><a href="#cb58-248" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="fu">aes</span>(<span class="at">group =</span> clu_id, <span class="at">color =</span> <span class="fu">as.factor</span>(clu_id))) <span class="sc">+</span></span>
<span id="cb58-249"><a href="#cb58-249" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb58-250"><a href="#cb58-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb58-251"><a href="#cb58-251" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"PPTV scores vs EWR scores by classroom"</span>, <span class="at">x =</span> <span class="st">"PPTV scores"</span>, <span class="at">y =</span> <span class="st">"EWR scores"</span>)</span>
<span id="cb58-252"><a href="#cb58-252" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-253"><a href="#cb58-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-256"><a href="#cb58-256" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-257"><a href="#cb58-257" aria-hidden="true" tabindex="-1"></a><span class="co"># fig 2</span></span>
<span id="cb58-258"><a href="#cb58-258" aria-hidden="true" tabindex="-1"></a><span class="co"># bubble plots</span></span>
<span id="cb58-259"><a href="#cb58-259" aria-hidden="true" tabindex="-1"></a><span class="co"># PPVT_FallK and ETW_SpringK</span></span>
<span id="cb58-260"><a href="#cb58-260" aria-hidden="true" tabindex="-1"></a>p1_df <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb58-261"><a href="#cb58-261" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(clu_id) <span class="sc">%&gt;%</span></span>
<span id="cb58-262"><a href="#cb58-262" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb58-263"><a href="#cb58-263" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_PPVT_FallK =</span> <span class="fu">mean</span>(PPVT_FallK, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb58-264"><a href="#cb58-264" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_ETW_SpringK =</span> <span class="fu">mean</span>(ETW_SpringK, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb58-265"><a href="#cb58-265" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_students =</span> <span class="fu">n</span>())</span>
<span id="cb58-266"><a href="#cb58-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-267"><a href="#cb58-267" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">=</span> <span class="fu">ggplot</span>(p1_df, <span class="fu">aes</span>(<span class="at">x =</span> mean_PPVT_FallK, <span class="at">y =</span> mean_ETW_SpringK, <span class="at">size =</span> n_students)) <span class="sc">+</span></span>
<span id="cb58-268"><a href="#cb58-268" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">5</span>, <span class="at">color =</span> <span class="st">"#6096ba"</span>) <span class="sc">+</span></span>
<span id="cb58-269"><a href="#cb58-269" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">12</span>), <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb58-270"><a href="#cb58-270" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Peabody Picture Vocabulary Test (PPVT) Scores by</span><span class="sc">\n</span><span class="st">Expressive Target Word Measure (ETW)"</span>,</span>
<span id="cb58-271"><a href="#cb58-271" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Mean PPVT"</span>,</span>
<span id="cb58-272"><a href="#cb58-272" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mean ETW"</span>) <span class="sc">+</span></span>
<span id="cb58-273"><a href="#cb58-273" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb58-274"><a href="#cb58-274" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb58-275"><a href="#cb58-275" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb58-276"><a href="#cb58-276" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb58-277"><a href="#cb58-277" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb58-278"><a href="#cb58-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-279"><a href="#cb58-279" aria-hidden="true" tabindex="-1"></a><span class="co"># ETW_SpringK and TVT</span></span>
<span id="cb58-280"><a href="#cb58-280" aria-hidden="true" tabindex="-1"></a>p2_df <span class="ot">=</span> data <span class="sc">%&gt;%</span></span>
<span id="cb58-281"><a href="#cb58-281" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(clu_id, TRT) <span class="sc">%&gt;%</span></span>
<span id="cb58-282"><a href="#cb58-282" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_ETW_SpringK =</span> <span class="fu">mean</span>(ETW_SpringK, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb58-283"><a href="#cb58-283" aria-hidden="true" tabindex="-1"></a>            <span class="at">n_students =</span> <span class="fu">n</span>())</span>
<span id="cb58-284"><a href="#cb58-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-285"><a href="#cb58-285" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">=</span> <span class="fu">ggplot</span>(p2_df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(TRT), <span class="at">y =</span> mean_ETW_SpringK)) <span class="sc">+</span></span>
<span id="cb58-286"><a href="#cb58-286" aria-hidden="true" tabindex="-1"></a>  ggdist<span class="sc">::</span><span class="fu">stat_halfeye</span>(</span>
<span id="cb58-287"><a href="#cb58-287" aria-hidden="true" tabindex="-1"></a>    <span class="at">adjust =</span> .<span class="dv">5</span>,</span>
<span id="cb58-288"><a href="#cb58-288" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> .<span class="dv">4</span>,</span>
<span id="cb58-289"><a href="#cb58-289" aria-hidden="true" tabindex="-1"></a>    <span class="at">.width =</span> <span class="dv">0</span>,</span>
<span id="cb58-290"><a href="#cb58-290" aria-hidden="true" tabindex="-1"></a>    <span class="at">justification =</span> <span class="sc">-</span>.<span class="dv">9</span>,</span>
<span id="cb58-291"><a href="#cb58-291" aria-hidden="true" tabindex="-1"></a>    <span class="at">point_colour =</span> <span class="cn">NA</span>,</span>
<span id="cb58-292"><a href="#cb58-292" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"#6096ba"</span></span>
<span id="cb58-293"><a href="#cb58-293" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb58-294"><a href="#cb58-294" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="fu">factor</span>(clu_id), <span class="at">size =</span> n_students), <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb58-295"><a href="#cb58-295" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">size =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb58-296"><a href="#cb58-296" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Expressive Target Word Measure (ETW) Scores</span><span class="sc">\n</span><span class="st">by Condition"</span>,</span>
<span id="cb58-297"><a href="#cb58-297" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Condition"</span>,</span>
<span id="cb58-298"><a href="#cb58-298" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb58-299"><a href="#cb58-299" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"Treatment"</span>)) <span class="sc">+</span></span>
<span id="cb58-300"><a href="#cb58-300" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb58-301"><a href="#cb58-301" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb58-302"><a href="#cb58-302" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb58-303"><a href="#cb58-303" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>)</span>
<span id="cb58-304"><a href="#cb58-304" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb58-305"><a href="#cb58-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-306"><a href="#cb58-306" aria-hidden="true" tabindex="-1"></a>combined_plot <span class="ot">=</span> p1 <span class="sc">|</span> p2</span>
<span id="cb58-307"><a href="#cb58-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-308"><a href="#cb58-308" aria-hidden="true" tabindex="-1"></a>caption_text <span class="ot">=</span> <span class="st">"Figure 1.</span><span class="sc">\n</span><span class="st">A: Mean classroom scores on the PPVT and ETW. Each 'bubble' represents a cluster or classroom.</span><span class="sc">\n</span><span class="st">B: ETW scores by experimental condition. Each bubble represents the average ETW score for a classroom.</span><span class="sc">\n</span><span class="st">Larger bubbles represent pairs containing more students."</span></span>
<span id="cb58-309"><a href="#cb58-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-310"><a href="#cb58-310" aria-hidden="true" tabindex="-1"></a>annotated_plot <span class="ot">=</span> combined_plot <span class="sc">&amp;</span></span>
<span id="cb58-311"><a href="#cb58-311" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_annotation</span>(</span>
<span id="cb58-312"><a href="#cb58-312" aria-hidden="true" tabindex="-1"></a>    <span class="at">tag_levels =</span> <span class="st">"A"</span>,</span>
<span id="cb58-313"><a href="#cb58-313" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> caption_text,</span>
<span id="cb58-314"><a href="#cb58-314" aria-hidden="true" tabindex="-1"></a>    <span class="at">theme =</span> <span class="fu">theme</span>(</span>
<span id="cb58-315"><a href="#cb58-315" aria-hidden="true" tabindex="-1"></a>      <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">hjust =</span> <span class="dv">0</span>)</span>
<span id="cb58-316"><a href="#cb58-316" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb58-317"><a href="#cb58-317" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb58-318"><a href="#cb58-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-319"><a href="#cb58-319" aria-hidden="true" tabindex="-1"></a>annotated_plot</span>
<span id="cb58-320"><a href="#cb58-320" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-321"><a href="#cb58-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-322"><a href="#cb58-322" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model comparisons</span></span>
<span id="cb58-323"><a href="#cb58-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-324"><a href="#cb58-324" aria-hidden="true" tabindex="-1"></a>Q5. Fit an unconditional means (null model), and print its summary</span>
<span id="cb58-325"><a href="#cb58-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-326"><a href="#cb58-326" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb58-327"><a href="#cb58-327" aria-hidden="true" tabindex="-1"></a>make sure you have loaded <span class="in">`lmerTest`</span> to get *p*-values</span>
<span id="cb58-328"><a href="#cb58-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-329"><a href="#cb58-329" aria-hidden="true" tabindex="-1"></a>When you load lmerTest, it modifies how summary() works on lmer models.</span>
<span id="cb58-330"><a href="#cb58-330" aria-hidden="true" tabindex="-1"></a>This happens automatically, and there isn't a specific new function you</span>
<span id="cb58-331"><a href="#cb58-331" aria-hidden="true" tabindex="-1"></a>need to call.</span>
<span id="cb58-332"><a href="#cb58-332" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb58-333"><a href="#cb58-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-334"><a href="#cb58-334" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb58-335"><a href="#cb58-335" aria-hidden="true" tabindex="-1"></a>The "model" with linear regression sets the intercept to be mean The</span>
<span id="cb58-336"><a href="#cb58-336" aria-hidden="true" tabindex="-1"></a>unconditional means "null model" ends up setting the group intercepts to</span>
<span id="cb58-337"><a href="#cb58-337" aria-hidden="true" tabindex="-1"></a>group means. Neither of these models have slopes.</span>
<span id="cb58-338"><a href="#cb58-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-339"><a href="#cb58-339" aria-hidden="true" tabindex="-1"></a>Null model in lm() --- lm(Y \~ 1) Null model in lmer() --- lm(Y \~ 1 +</span>
<span id="cb58-340"><a href="#cb58-340" aria-hidden="true" tabindex="-1"></a>(1\|grouping_factor))</span>
<span id="cb58-341"><a href="#cb58-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-342"><a href="#cb58-342" aria-hidden="true" tabindex="-1"></a>REML (Restricted Maximum Likelihood) is better for variance estimation -</span>
<span id="cb58-343"><a href="#cb58-343" aria-hidden="true" tabindex="-1"></a>and that's exactly what null models are trying to do for the data</span>
<span id="cb58-344"><a href="#cb58-344" aria-hidden="true" tabindex="-1"></a>without considering any fixed effect predictor. So, choose REML in your</span>
<span id="cb58-345"><a href="#cb58-345" aria-hidden="true" tabindex="-1"></a>lmer call.</span>
<span id="cb58-346"><a href="#cb58-346" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb58-347"><a href="#cb58-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-348"><a href="#cb58-348" aria-hidden="true" tabindex="-1"></a>::: Answer. ::: cell</span>
<span id="cb58-349"><a href="#cb58-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-350"><a href="#cb58-350" aria-hidden="true" tabindex="-1"></a><span class="in">```{r .cell-code}</span></span>
<span id="cb58-351"><a href="#cb58-351" aria-hidden="true" tabindex="-1"></a><span class="in">model1 &lt;- lmer(ETW_SpringK ~ 1 + (1|clu_id),</span></span>
<span id="cb58-352"><a href="#cb58-352" aria-hidden="true" tabindex="-1"></a><span class="in">               data = data)</span></span>
<span id="cb58-353"><a href="#cb58-353" aria-hidden="true" tabindex="-1"></a><span class="in">summary(model1)</span></span>
<span id="cb58-354"><a href="#cb58-354" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-355"><a href="#cb58-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-356"><a href="#cb58-356" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb58-357"><a href="#cb58-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-358"><a href="#cb58-358" aria-hidden="true" tabindex="-1"></a>Q6. The intraclass correlation coefficient (ICC) measures proportion of</span>
<span id="cb58-359"><a href="#cb58-359" aria-hidden="true" tabindex="-1"></a>total variance due to group membership Calculate it manually for the</span>
<span id="cb58-360"><a href="#cb58-360" aria-hidden="true" tabindex="-1"></a>fitted model from the output, and print it out. Is multilevel modeling</span>
<span id="cb58-361"><a href="#cb58-361" aria-hidden="true" tabindex="-1"></a>warranted here?</span>
<span id="cb58-362"><a href="#cb58-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-363"><a href="#cb58-363" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb58-364"><a href="#cb58-364" aria-hidden="true" tabindex="-1"></a>A common heuristic: ICC <span class="sc">\&lt;</span> 0.05 = Probably not needed ICC <span class="sc">\&gt;</span> 0.05-0.1 =</span>
<span id="cb58-365"><a href="#cb58-365" aria-hidden="true" tabindex="-1"></a>Multilevel warranted ICC <span class="sc">\&gt;</span> 0.1 = Strong indication for multilevel</span>
<span id="cb58-366"><a href="#cb58-366" aria-hidden="true" tabindex="-1"></a>models.</span>
<span id="cb58-367"><a href="#cb58-367" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb58-368"><a href="#cb58-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-371"><a href="#cb58-371" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-372"><a href="#cb58-372" aria-hidden="true" tabindex="-1"></a><span class="co">#TYPE YOUR CODE BELOW</span></span>
<span id="cb58-373"><a href="#cb58-373" aria-hidden="true" tabindex="-1"></a><span class="co"># a. Extract the variance components from the model output</span></span>
<span id="cb58-374"><a href="#cb58-374" aria-hidden="true" tabindex="-1"></a><span class="co"># b. Calculate ICC</span></span>
<span id="cb58-375"><a href="#cb58-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-376"><a href="#cb58-376" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-377"><a href="#cb58-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-378"><a href="#cb58-378" aria-hidden="true" tabindex="-1"></a>Now use the <span class="in">`icc`</span> function in easystats / performance package to</span>
<span id="cb58-379"><a href="#cb58-379" aria-hidden="true" tabindex="-1"></a>calculate the icc</span>
<span id="cb58-380"><a href="#cb58-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-381"><a href="#cb58-381" aria-hidden="true" tabindex="-1"></a>Answers:</span>
<span id="cb58-382"><a href="#cb58-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-385"><a href="#cb58-385" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-386"><a href="#cb58-386" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the variance components from the model output</span></span>
<span id="cb58-387"><a href="#cb58-387" aria-hidden="true" tabindex="-1"></a>cluster_variance <span class="ot">&lt;-</span> <span class="fl">19.91</span></span>
<span id="cb58-388"><a href="#cb58-388" aria-hidden="true" tabindex="-1"></a>residual_variance <span class="ot">&lt;-</span> <span class="fl">104.43</span></span>
<span id="cb58-389"><a href="#cb58-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-390"><a href="#cb58-390" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate ICC</span></span>
<span id="cb58-391"><a href="#cb58-391" aria-hidden="true" tabindex="-1"></a>icc <span class="ot">&lt;-</span> cluster_variance <span class="sc">/</span> (cluster_variance <span class="sc">+</span> residual_variance)</span>
<span id="cb58-392"><a href="#cb58-392" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(icc, <span class="dv">4</span>)</span>
<span id="cb58-393"><a href="#cb58-393" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-394"><a href="#cb58-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-395"><a href="#cb58-395" aria-hidden="true" tabindex="-1"></a>Now use the <span class="in">`icc`</span> function in easystats / performance package to</span>
<span id="cb58-396"><a href="#cb58-396" aria-hidden="true" tabindex="-1"></a>calculate the icc</span>
<span id="cb58-397"><a href="#cb58-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-400"><a href="#cb58-400" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-401"><a href="#cb58-401" aria-hidden="true" tabindex="-1"></a><span class="co">#easystats</span></span>
<span id="cb58-402"><a href="#cb58-402" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">icc</span>(model1)</span>
<span id="cb58-403"><a href="#cb58-403" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-404"><a href="#cb58-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-405"><a href="#cb58-405" aria-hidden="true" tabindex="-1"></a>Is multilevel modeling warranted here? Yep! What does the ICC mean? It</span>
<span id="cb58-406"><a href="#cb58-406" aria-hidden="true" tabindex="-1"></a>tells us how much variability there is between clusters. It also tells</span>
<span id="cb58-407"><a href="#cb58-407" aria-hidden="true" tabindex="-1"></a>how how correlated our level 1 units are to one another. In this case,</span>
<span id="cb58-408"><a href="#cb58-408" aria-hidden="true" tabindex="-1"></a>we have observe an ICC of 0.160, which indicates that 16% of the total</span>
<span id="cb58-409"><a href="#cb58-409" aria-hidden="true" tabindex="-1"></a>variance in our outcome variable (students' vocabulary knowledge scores</span>
<span id="cb58-410"><a href="#cb58-410" aria-hidden="true" tabindex="-1"></a><span class="in">`ETW_SpringK`</span>) is attributable to differences between classroom (Level 2</span>
<span id="cb58-411"><a href="#cb58-411" aria-hidden="true" tabindex="-1"></a>variance).</span>
<span id="cb58-412"><a href="#cb58-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-413"><a href="#cb58-413" aria-hidden="true" tabindex="-1"></a>Q7. Build up from the last model. Fit a model that includes all level 1</span>
<span id="cb58-414"><a href="#cb58-414" aria-hidden="true" tabindex="-1"></a>variables (no interaction)</span>
<span id="cb58-415"><a href="#cb58-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-418"><a href="#cb58-418" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-419"><a href="#cb58-419" aria-hidden="true" tabindex="-1"></a><span class="co">#Type your code here</span></span>
<span id="cb58-420"><a href="#cb58-420" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-421"><a href="#cb58-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-422"><a href="#cb58-422" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb58-423"><a href="#cb58-423" aria-hidden="true" tabindex="-1"></a>Tip: You're building from the last model. So you're building on the</span>
<span id="cb58-424"><a href="#cb58-424" aria-hidden="true" tabindex="-1"></a>clustering structure. So, you'd make sure to keep the random intercept</span>
<span id="cb58-425"><a href="#cb58-425" aria-hidden="true" tabindex="-1"></a>intact.</span>
<span id="cb58-426"><a href="#cb58-426" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb58-427"><a href="#cb58-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-428"><a href="#cb58-428" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb58-429"><a href="#cb58-429" aria-hidden="true" tabindex="-1"></a>Maximum likelihood (as opposed Restricted maximum likelihood is best</span>
<span id="cb58-430"><a href="#cb58-430" aria-hidden="true" tabindex="-1"></a>once you begin to have fixed effects), so set your REML flag</span>
<span id="cb58-431"><a href="#cb58-431" aria-hidden="true" tabindex="-1"></a>appropriately. By default it's True.</span>
<span id="cb58-432"><a href="#cb58-432" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb58-433"><a href="#cb58-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-434"><a href="#cb58-434" aria-hidden="true" tabindex="-1"></a>Answer:</span>
<span id="cb58-435"><a href="#cb58-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-438"><a href="#cb58-438" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-439"><a href="#cb58-439" aria-hidden="true" tabindex="-1"></a>level_1_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(ETW_SpringK <span class="sc">~</span> TRT <span class="sc">+</span> PPVT_FallK <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>clu_id), <span class="at">data =</span> data)</span>
<span id="cb58-440"><a href="#cb58-440" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(level_1_model)</span>
<span id="cb58-441"><a href="#cb58-441" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-442"><a href="#cb58-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-443"><a href="#cb58-443" aria-hidden="true" tabindex="-1"></a>Q8. Fit a model that includes the fixed interaction between the level-1</span>
<span id="cb58-444"><a href="#cb58-444" aria-hidden="true" tabindex="-1"></a>variables</span>
<span id="cb58-445"><a href="#cb58-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-446"><a href="#cb58-446" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb58-447"><a href="#cb58-447" aria-hidden="true" tabindex="-1"></a>Note, in case you're ever counfused about this in R formulas format Y \~</span>
<span id="cb58-448"><a href="#cb58-448" aria-hidden="true" tabindex="-1"></a>A + B + A:B (main effects + interaction term) is the same as Y \~ A<span class="sc">\*</span>B</span>
<span id="cb58-449"><a href="#cb58-449" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb58-450"><a href="#cb58-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-451"><a href="#cb58-451" aria-hidden="true" tabindex="-1"></a>Answer:</span>
<span id="cb58-452"><a href="#cb58-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-455"><a href="#cb58-455" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-456"><a href="#cb58-456" aria-hidden="true" tabindex="-1"></a>interaction_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(ETW_SpringK <span class="sc">~</span> TRT <span class="sc">*</span> PPVT_FallK <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>clu_id), <span class="at">data =</span> data)</span>
<span id="cb58-457"><a href="#cb58-457" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(interaction_model)</span>
<span id="cb58-458"><a href="#cb58-458" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-459"><a href="#cb58-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-460"><a href="#cb58-460" aria-hidden="true" tabindex="-1"></a>Q9. Compare the main effects and interaction models. Which model is the</span>
<span id="cb58-461"><a href="#cb58-461" aria-hidden="true" tabindex="-1"></a>best? Try the likelihood ratio test, AIC and BIC, and jot down your</span>
<span id="cb58-462"><a href="#cb58-462" aria-hidden="true" tabindex="-1"></a>thoughts.</span>
<span id="cb58-463"><a href="#cb58-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-464"><a href="#cb58-464" aria-hidden="true" tabindex="-1"></a>Answer:</span>
<span id="cb58-465"><a href="#cb58-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-468"><a href="#cb58-468" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-469"><a href="#cb58-469" aria-hidden="true" tabindex="-1"></a><span class="fu">test_likelihoodratio</span>(level_1_model, interaction_model, <span class="at">REML=</span><span class="cn">FALSE</span>)</span>
<span id="cb58-470"><a href="#cb58-470" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-471"><a href="#cb58-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-472"><a href="#cb58-472" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb58-473"><a href="#cb58-473" aria-hidden="true" tabindex="-1"></a>AIC and BIC can be used with the models you've already fitted.</span>
<span id="cb58-474"><a href="#cb58-474" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-475"><a href="#cb58-475" aria-hidden="true" tabindex="-1"></a>However, for likelihood ratio tests of nested models, Maximum likelihood</span>
<span id="cb58-476"><a href="#cb58-476" aria-hidden="true" tabindex="-1"></a>(as opposed Restricted maximum likelihood) is best for model comparison.</span>
<span id="cb58-477"><a href="#cb58-477" aria-hidden="true" tabindex="-1"></a>So such a likelihood ratio test will require models to be re-fit with</span>
<span id="cb58-478"><a href="#cb58-478" aria-hidden="true" tabindex="-1"></a>REML=TRUE, just to give better model comparison results. )</span>
<span id="cb58-479"><a href="#cb58-479" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb58-480"><a href="#cb58-480" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-481"><a href="#cb58-481" aria-hidden="true" tabindex="-1"></a>Answer: - The interaction model is statistically superior to the main</span>
<span id="cb58-482"><a href="#cb58-482" aria-hidden="true" tabindex="-1"></a>effects model, as indicated by lower AIC and BIC scores. This is further</span>
<span id="cb58-483"><a href="#cb58-483" aria-hidden="true" tabindex="-1"></a>confirmed by a statistically significant likelihood ratio test</span>
<span id="cb58-484"><a href="#cb58-484" aria-hidden="true" tabindex="-1"></a>($\chi^2 = 8.39, p = .0038$). This suggests that including the</span>
<span id="cb58-485"><a href="#cb58-485" aria-hidden="true" tabindex="-1"></a>interaction between <span class="in">`TRT`</span> and <span class="in">`PPVT_FallK`</span> provides a better fit to the</span>
<span id="cb58-486"><a href="#cb58-486" aria-hidden="true" tabindex="-1"></a>data.</span>
<span id="cb58-487"><a href="#cb58-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-488"><a href="#cb58-488" aria-hidden="true" tabindex="-1"></a>Q10. Use the best model from above and fit a model that adds random</span>
<span id="cb58-489"><a href="#cb58-489" aria-hidden="true" tabindex="-1"></a>slopes for <span class="in">`TRT`</span></span>
<span id="cb58-490"><a href="#cb58-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-491"><a href="#cb58-491" aria-hidden="true" tabindex="-1"></a>Answer:</span>
<span id="cb58-492"><a href="#cb58-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-495"><a href="#cb58-495" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-496"><a href="#cb58-496" aria-hidden="true" tabindex="-1"></a>best_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(ETW_SpringK <span class="sc">~</span> TRT <span class="sc">*</span> PPVT_FallK <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span> TRT<span class="sc">|</span>clu_id), <span class="at">data =</span> data)</span>
<span id="cb58-497"><a href="#cb58-497" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-498"><a href="#cb58-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-499"><a href="#cb58-499" aria-hidden="true" tabindex="-1"></a>Next, let's create a model with a random slope for treatment and PPVT</span>
<span id="cb58-500"><a href="#cb58-500" aria-hidden="true" tabindex="-1"></a>scores. This will be our maximal model.</span>
<span id="cb58-501"><a href="#cb58-501" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-502"><a href="#cb58-502" aria-hidden="true" tabindex="-1"></a>::: callout-warning</span>
<span id="cb58-503"><a href="#cb58-503" aria-hidden="true" tabindex="-1"></a>We could include a random slope for the interaction between the two, but</span>
<span id="cb58-504"><a href="#cb58-504" aria-hidden="true" tabindex="-1"></a>we only have 6 students per classroom and makes our model too complex.</span>
<span id="cb58-505"><a href="#cb58-505" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb58-506"><a href="#cb58-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-509"><a href="#cb58-509" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-510"><a href="#cb58-510" aria-hidden="true" tabindex="-1"></a>complex_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(ETW_SpringK <span class="sc">~</span> TRT <span class="sc">*</span> PPVT_FallK <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> TRT <span class="sc">+</span> PPVT_FallK<span class="sc">|</span>clu_id), <span class="at">data =</span> data)</span>
<span id="cb58-511"><a href="#cb58-511" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-512"><a href="#cb58-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-515"><a href="#cb58-515" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-516"><a href="#cb58-516" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb58-517"><a href="#cb58-517" aria-hidden="true" tabindex="-1"></a><span class="fu">isSingular</span>(complex_model)</span>
<span id="cb58-518"><a href="#cb58-518" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-519"><a href="#cb58-519" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-520"><a href="#cb58-520" aria-hidden="true" tabindex="-1"></a>Take a look at the maximal model output. What is the warning message? We</span>
<span id="cb58-521"><a href="#cb58-521" aria-hidden="true" tabindex="-1"></a>observe that the more complex model has a singular fit, which likely</span>
<span id="cb58-522"><a href="#cb58-522" aria-hidden="true" tabindex="-1"></a>results from overfitting the data. In particular, the more complex model</span>
<span id="cb58-523"><a href="#cb58-523" aria-hidden="true" tabindex="-1"></a>contains random slopes for both <span class="in">`TRT`</span> and <span class="in">`PPVT_FallK`</span> within clusters</span>
<span id="cb58-524"><a href="#cb58-524" aria-hidden="true" tabindex="-1"></a>(<span class="in">`clu_id`</span>). We can infer that there is not enough variation in <span class="in">`TRT`</span> or</span>
<span id="cb58-525"><a href="#cb58-525" aria-hidden="true" tabindex="-1"></a><span class="in">`PPVT_FallK`</span> within clusters, so the model may not be able to estimate</span>
<span id="cb58-526"><a href="#cb58-526" aria-hidden="true" tabindex="-1"></a>random effects reliably. To get rid of this warning, we could reduce</span>
<span id="cb58-527"><a href="#cb58-527" aria-hidden="true" tabindex="-1"></a>complexity in the model by removing some of the random slopes.</span>
<span id="cb58-528"><a href="#cb58-528" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-529"><a href="#cb58-529" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model interpretation</span></span>
<span id="cb58-530"><a href="#cb58-530" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-531"><a href="#cb58-531" aria-hidden="true" tabindex="-1"></a>Through model comparisons like before, we can tell that the model with</span>
<span id="cb58-532"><a href="#cb58-532" aria-hidden="true" tabindex="-1"></a>random slopes for TRT and random intercepts for classroom is the best.</span>
<span id="cb58-533"><a href="#cb58-533" aria-hidden="true" tabindex="-1"></a>Now let's use this best model and examine the fixed effects.</span>
<span id="cb58-534"><a href="#cb58-534" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-535"><a href="#cb58-535" aria-hidden="true" tabindex="-1"></a>Q 11. Please interpret these effects/coefs in a sentence or two.</span>
<span id="cb58-536"><a href="#cb58-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-539"><a href="#cb58-539" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-540"><a href="#cb58-540" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the best model and output a nice summary table of results.</span></span>
<span id="cb58-541"><a href="#cb58-541" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex) <span class="co"># load afex in</span></span>
<span id="cb58-542"><a href="#cb58-542" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-543"><a href="#cb58-543" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">mixed</span>(ETW_SpringK <span class="sc">~</span> TRT <span class="sc">*</span> PPVT_FallK <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span> TRT<span class="sc">|</span>clu_id), <span class="at">data=</span>data)</span>
<span id="cb58-544"><a href="#cb58-544" aria-hidden="true" tabindex="-1"></a><span class="fu">nice</span>(m) <span class="sc">%&gt;%</span></span>
<span id="cb58-545"><a href="#cb58-545" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span>
<span id="cb58-546"><a href="#cb58-546" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-547"><a href="#cb58-547" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-550"><a href="#cb58-550" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-551"><a href="#cb58-551" aria-hidden="true" tabindex="-1"></a><span class="fu">emtrends</span>(best_model, <span class="sc">~</span>TRT, <span class="at">var=</span><span class="st">"PPVT_FallK"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb58-552"><a href="#cb58-552" aria-hidden="true" tabindex="-1"></a>  <span class="fu">test</span>() <span class="sc">%&gt;%</span></span>
<span id="cb58-553"><a href="#cb58-553" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span>
<span id="cb58-554"><a href="#cb58-554" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-555"><a href="#cb58-555" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-556"><a href="#cb58-556" aria-hidden="true" tabindex="-1"></a>Let's evaluate the variance components of the model.</span>
<span id="cb58-557"><a href="#cb58-557" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-560"><a href="#cb58-560" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-561"><a href="#cb58-561" aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(best_model, <span class="at">effects=</span><span class="st">"random"</span>) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span>
<span id="cb58-562"><a href="#cb58-562" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-563"><a href="#cb58-563" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-564"><a href="#cb58-564" aria-hidden="true" tabindex="-1"></a>Q12. How do you interpet the modeling results, in terms of varaince in</span>
<span id="cb58-565"><a href="#cb58-565" aria-hidden="true" tabindex="-1"></a>intercept, treatment effect, and residuals?</span>
<span id="cb58-566"><a href="#cb58-566" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-567"><a href="#cb58-567" aria-hidden="true" tabindex="-1"></a>Answers: - The variance is 25.01 for the intercepts across the different</span>
<span id="cb58-568"><a href="#cb58-568" aria-hidden="true" tabindex="-1"></a>classrooms (<span class="in">`clu_id`</span>). This suggests there is substantial variability in</span>
<span id="cb58-569"><a href="#cb58-569" aria-hidden="true" tabindex="-1"></a>the baseline <span class="in">`ETW_SpringK`</span> scores that can be attributed to differences</span>
<span id="cb58-570"><a href="#cb58-570" aria-hidden="true" tabindex="-1"></a>between classrooms before considering <span class="in">`TRT`</span> or <span class="in">`PPVT_FallK`</span> scores.</span>
<span id="cb58-571"><a href="#cb58-571" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-572"><a href="#cb58-572" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The variance associated with the treatment effect (<span class="in">`TRT`</span>) across</span>
<span id="cb58-573"><a href="#cb58-573" aria-hidden="true" tabindex="-1"></a>    classrooms is 45.51. This suggests significant variability in how</span>
<span id="cb58-574"><a href="#cb58-574" aria-hidden="true" tabindex="-1"></a>    the treatment effect on <span class="in">`ETW_SpringK`</span> scores differs from one</span>
<span id="cb58-575"><a href="#cb58-575" aria-hidden="true" tabindex="-1"></a>    classroom to another.</span>
<span id="cb58-576"><a href="#cb58-576" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-577"><a href="#cb58-577" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The variance of residuals is 57.02. This indicates the remaining</span>
<span id="cb58-578"><a href="#cb58-578" aria-hidden="true" tabindex="-1"></a>    within-classroom variance in student scores that cannot be explained</span>
<span id="cb58-579"><a href="#cb58-579" aria-hidden="true" tabindex="-1"></a>    by the model's fixed effects or the classroom-level random effects.</span>
<span id="cb58-580"><a href="#cb58-580" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-581"><a href="#cb58-581" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Overall, our variance components are significant for both the random</span>
<span id="cb58-582"><a href="#cb58-582" aria-hidden="true" tabindex="-1"></a>    intercept and slope for <span class="in">`TRT`</span>. This suggests that multilevel</span>
<span id="cb58-583"><a href="#cb58-583" aria-hidden="true" tabindex="-1"></a>    modeling is, indeed, appropriate and necessary to account for the</span>
<span id="cb58-584"><a href="#cb58-584" aria-hidden="true" tabindex="-1"></a>    clustering of student scores within classrooms and the variability</span>
<span id="cb58-585"><a href="#cb58-585" aria-hidden="true" tabindex="-1"></a>    in treatment effects across classrooms.</span>
<span id="cb58-586"><a href="#cb58-586" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-587"><a href="#cb58-587" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model fit</span></span>
<span id="cb58-588"><a href="#cb58-588" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-589"><a href="#cb58-589" aria-hidden="true" tabindex="-1"></a>We can then calculate the conditional and marginal pseudo-$R^2$ of the</span>
<span id="cb58-590"><a href="#cb58-590" aria-hidden="true" tabindex="-1"></a>model</span>
<span id="cb58-591"><a href="#cb58-591" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-594"><a href="#cb58-594" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-595"><a href="#cb58-595" aria-hidden="true" tabindex="-1"></a><span class="fu">r2</span>(best_model)</span>
<span id="cb58-596"><a href="#cb58-596" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-597"><a href="#cb58-597" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-598"><a href="#cb58-598" aria-hidden="true" tabindex="-1"></a>The semi-$R^2$ for the <span class="in">`PPVT`</span> variable is calculated using the <span class="in">`partR2`</span></span>
<span id="cb58-599"><a href="#cb58-599" aria-hidden="true" tabindex="-1"></a>function from <span class="in">`partR2`</span> package</span>
<span id="cb58-600"><a href="#cb58-600" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-603"><a href="#cb58-603" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-604"><a href="#cb58-604" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(partR2)</span>
<span id="cb58-605"><a href="#cb58-605" aria-hidden="true" tabindex="-1"></a><span class="fu">partR2</span>(best_model, <span class="at">data =</span> data, <span class="at">partvars =</span> <span class="fu">c</span>(<span class="st">"PPVT_FallK"</span>), <span class="at">R2_type =</span> <span class="st">"marginal"</span>)</span>
<span id="cb58-606"><a href="#cb58-606" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-607"><a href="#cb58-607" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-608"><a href="#cb58-608" aria-hidden="true" tabindex="-1"></a>We can visualize the random intercepts and slopes in your model</span>
<span id="cb58-609"><a href="#cb58-609" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-612"><a href="#cb58-612" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-613"><a href="#cb58-613" aria-hidden="true" tabindex="-1"></a>random <span class="ot">&lt;-</span> <span class="fu">estimate_grouplevel</span>(best_model)</span>
<span id="cb58-614"><a href="#cb58-614" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(random) <span class="sc">+</span> <span class="fu">theme_lucid</span>()</span>
<span id="cb58-615"><a href="#cb58-615" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-616"><a href="#cb58-616" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-617"><a href="#cb58-617" aria-hidden="true" tabindex="-1"></a><span class="fu">## Assumptions</span></span>
<span id="cb58-618"><a href="#cb58-618" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-619"><a href="#cb58-619" aria-hidden="true" tabindex="-1"></a>Q12. Check model assumptions with <span class="in">`check_model`</span>. Do any of the</span>
<span id="cb58-620"><a href="#cb58-620" aria-hidden="true" tabindex="-1"></a>assumptions appear to be violated?</span>
<span id="cb58-621"><a href="#cb58-621" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-624"><a href="#cb58-624" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-625"><a href="#cb58-625" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(best_model)</span>
<span id="cb58-626"><a href="#cb58-626" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-627"><a href="#cb58-627" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-628"><a href="#cb58-628" aria-hidden="true" tabindex="-1"></a>Answer:</span>
<span id="cb58-629"><a href="#cb58-629" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-630"><a href="#cb58-630" aria-hidden="true" tabindex="-1"></a>We can also visualize the interaction between <span class="in">`TRT`</span> and <span class="in">`PPVT`</span> score on</span>
<span id="cb58-631"><a href="#cb58-631" aria-hidden="true" tabindex="-1"></a>ETW (I would check out the <span class="in">`interactions`</span> or <span class="in">`ggeffects`</span> packages. They</span>
<span id="cb58-632"><a href="#cb58-632" aria-hidden="true" tabindex="-1"></a>have some nice features for plotting interactions.)</span>
<span id="cb58-633"><a href="#cb58-633" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-636"><a href="#cb58-636" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-637"><a href="#cb58-637" aria-hidden="true" tabindex="-1"></a><span class="fu">interact_plot</span>(best_model, <span class="at">pred =</span> <span class="st">"PPVT_FallK"</span>, <span class="at">modx =</span> <span class="st">"TRT"</span>, <span class="at">data =</span> data)</span>
<span id="cb58-638"><a href="#cb58-638" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-639"><a href="#cb58-639" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-640"><a href="#cb58-640" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reporting Results</span></span>
<span id="cb58-641"><a href="#cb58-641" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-642"><a href="#cb58-642" aria-hidden="true" tabindex="-1"></a>Q14. Briefly highlight what you think needs to be present in the</span>
<span id="cb58-643"><a href="#cb58-643" aria-hidden="true" tabindex="-1"></a>results. I will share what a complete report would like in the solution.</span>
<span id="cb58-644"><a href="#cb58-644" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-645"><a href="#cb58-645" aria-hidden="true" tabindex="-1"></a>Write-up the results of your MLM model incorporating the above</span>
<span id="cb58-646"><a href="#cb58-646" aria-hidden="true" tabindex="-1"></a>information. This write-up should resemble what you would find in a</span>
<span id="cb58-647"><a href="#cb58-647" aria-hidden="true" tabindex="-1"></a>published paper. You can use the textbook for guidance and the <span class="in">`report`</span></span>
<span id="cb58-648"><a href="#cb58-648" aria-hidden="true" tabindex="-1"></a>function from <span class="in">`easystats`</span></span>
<span id="cb58-649"><a href="#cb58-649" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-650"><a href="#cb58-650" aria-hidden="true" tabindex="-1"></a>The present study investigated the impact of a vocabulary instruction</span>
<span id="cb58-651"><a href="#cb58-651" aria-hidden="true" tabindex="-1"></a>intervention on students' knowledge, using a nested data structure with</span>
<span id="cb58-652"><a href="#cb58-652" aria-hidden="true" tabindex="-1"></a>two levels: students (Level 1) nested within classrooms (Level 2). The</span>
<span id="cb58-653"><a href="#cb58-653" aria-hidden="true" tabindex="-1"></a>analysis included 1,427 students distributed across 222 classrooms.</span>
<span id="cb58-654"><a href="#cb58-654" aria-hidden="true" tabindex="-1"></a>Classrooms varied in size, with an average of approximately 6.4 students</span>
<span id="cb58-655"><a href="#cb58-655" aria-hidden="true" tabindex="-1"></a>per classroom ($SD = 2.2, range = <span class="co">[</span><span class="ot">2, 18</span><span class="co">]</span>$).</span>
<span id="cb58-656"><a href="#cb58-656" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-657"><a href="#cb58-657" aria-hidden="true" tabindex="-1"></a>The relationship between the intervention and vocabulary knowledge was</span>
<span id="cb58-658"><a href="#cb58-658" aria-hidden="true" tabindex="-1"></a>modeled using a multilevel linear model, represented by the following</span>
<span id="cb58-659"><a href="#cb58-659" aria-hidden="true" tabindex="-1"></a>equation:</span>
<span id="cb58-660"><a href="#cb58-660" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-663"><a href="#cb58-663" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-664"><a href="#cb58-664" aria-hidden="true" tabindex="-1"></a>equatiomatic<span class="sc">::</span><span class="fu">extract_eq</span>(best_model)</span>
<span id="cb58-665"><a href="#cb58-665" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb58-666"><a href="#cb58-666" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-667"><a href="#cb58-667" aria-hidden="true" tabindex="-1"></a>where $ETW<span class="sc">\_</span>SpringK$ is the student's score on the vocabulary knowledge</span>
<span id="cb58-668"><a href="#cb58-668" aria-hidden="true" tabindex="-1"></a>assessment, $TRT$ is the treatment condition, $PPVT<span class="sc">\_</span>FallK$ is the</span>
<span id="cb58-669"><a href="#cb58-669" aria-hidden="true" tabindex="-1"></a>Peabody Picture Vocabulary Test score, and $(1 + TRT|clu<span class="sc">\_</span>id)$</span>
<span id="cb58-670"><a href="#cb58-670" aria-hidden="true" tabindex="-1"></a>represents the random intercepts and slopes for treatment across</span>
<span id="cb58-671"><a href="#cb58-671" aria-hidden="true" tabindex="-1"></a>classrooms. Note that $ETW<span class="sc">\_</span>SpringK$, $TRT$, and $PPVT<span class="sc">\_</span>FallK$ are all</span>
<span id="cb58-672"><a href="#cb58-672" aria-hidden="true" tabindex="-1"></a>Level 1 variables, and $clu<span class="sc">\_</span>id$ is at Level 2. For the above analysis,</span>
<span id="cb58-673"><a href="#cb58-673" aria-hidden="true" tabindex="-1"></a>we mean centered $PPVT<span class="sc">\_</span>FallK$ within each cluster and deviation coded</span>
<span id="cb58-674"><a href="#cb58-674" aria-hidden="true" tabindex="-1"></a>$TRT$.</span>
<span id="cb58-675"><a href="#cb58-675" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-676"><a href="#cb58-676" aria-hidden="true" tabindex="-1"></a>Before settling on the above model, we estimated an unconditional means</span>
<span id="cb58-677"><a href="#cb58-677" aria-hidden="true" tabindex="-1"></a>(null) model and maximal model, which included a random slope for both</span>
<span id="cb58-678"><a href="#cb58-678" aria-hidden="true" tabindex="-1"></a>treatment and PPVT scores. We compared the above model ($df = 8$) to the</span>
<span id="cb58-679"><a href="#cb58-679" aria-hidden="true" tabindex="-1"></a>maximal model ($df = 11$) using a likelihood ratio test from the</span>
<span id="cb58-680"><a href="#cb58-680" aria-hidden="true" tabindex="-1"></a>easystats package (version 0.6.0). We found that the more complex model</span>
<span id="cb58-681"><a href="#cb58-681" aria-hidden="true" tabindex="-1"></a>did not significantly improve model fit ($\chi^2 = 4.85, p = 0.185$). We</span>
<span id="cb58-682"><a href="#cb58-682" aria-hidden="true" tabindex="-1"></a>therefore proceeded to use the simpler model for our analyses, as there</span>
<span id="cb58-683"><a href="#cb58-683" aria-hidden="true" tabindex="-1"></a>was not sufficient evidence to justify additional complexity in our</span>
<span id="cb58-684"><a href="#cb58-684" aria-hidden="true" tabindex="-1"></a>model.</span>
<span id="cb58-685"><a href="#cb58-685" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-686"><a href="#cb58-686" aria-hidden="true" tabindex="-1"></a>We checked our model assumptions (linearity, normality of residuals,</span>
<span id="cb58-687"><a href="#cb58-687" aria-hidden="true" tabindex="-1"></a>homoscedasticity, collinearity) visually, using diagnostic plots from</span>
<span id="cb58-688"><a href="#cb58-688" aria-hidden="true" tabindex="-1"></a>the performance package (version 0.10.5). Based on this visual</span>
<span id="cb58-689"><a href="#cb58-689" aria-hidden="true" tabindex="-1"></a>assessment, we found that all our model assumptions were satisfied. The</span>
<span id="cb58-690"><a href="#cb58-690" aria-hidden="true" tabindex="-1"></a>Intraclass Correlation Coefficient (ICC) for the outcome variable was</span>
<span id="cb58-691"><a href="#cb58-691" aria-hidden="true" tabindex="-1"></a>calculated as 0.16, suggesting that 16% of the variance in vocabulary</span>
<span id="cb58-692"><a href="#cb58-692" aria-hidden="true" tabindex="-1"></a>knowledge scores could be attributed to differences between classrooms.</span>
<span id="cb58-693"><a href="#cb58-693" aria-hidden="true" tabindex="-1"></a>The models were estimated using Restricted Maximum Likelihood (REML) to</span>
<span id="cb58-694"><a href="#cb58-694" aria-hidden="true" tabindex="-1"></a>account for the nested data structure. The lme4 package (version 1.1.34)</span>
<span id="cb58-695"><a href="#cb58-695" aria-hidden="true" tabindex="-1"></a>was used for fitting the model, with the interactions package (version</span>
<span id="cb58-696"><a href="#cb58-696" aria-hidden="true" tabindex="-1"></a>1.1.5) for estimating and plotting interactions.</span>
<span id="cb58-697"><a href="#cb58-697" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-698"><a href="#cb58-698" aria-hidden="true" tabindex="-1"></a>The fixed effects analysis revealed a significant intercept</span>
<span id="cb58-699"><a href="#cb58-699" aria-hidden="true" tabindex="-1"></a>($b = 13.47, SE = 0.40, t(209) = 34.03, p &lt; .001$), indicating a high</span>
<span id="cb58-700"><a href="#cb58-700" aria-hidden="true" tabindex="-1"></a>baseline level of vocabulary knowledge. The treatment effect was also</span>
<span id="cb58-701"><a href="#cb58-701" aria-hidden="true" tabindex="-1"></a>significant ($b = 10.47, SE = 0.62, t(213) = 17.02, p &lt; .001$),</span>
<span id="cb58-702"><a href="#cb58-702" aria-hidden="true" tabindex="-1"></a>suggesting that the treatment had a substantial positive impact on</span>
<span id="cb58-703"><a href="#cb58-703" aria-hidden="true" tabindex="-1"></a>vocabulary knowledge. Additionally, PPVT scores were positively</span>
<span id="cb58-704"><a href="#cb58-704" aria-hidden="true" tabindex="-1"></a>associated with ETW scores</span>
<span id="cb58-705"><a href="#cb58-705" aria-hidden="true" tabindex="-1"></a>($b = 0.43, SE = 0.04, t(1091) = 9.67, p &lt; .001$), indicating that</span>
<span id="cb58-706"><a href="#cb58-706" aria-hidden="true" tabindex="-1"></a>higher initial vocabulary levels were associated with higher</span>
<span id="cb58-707"><a href="#cb58-707" aria-hidden="true" tabindex="-1"></a>post-intervention vocabulary knowledge. The interaction between</span>
<span id="cb58-708"><a href="#cb58-708" aria-hidden="true" tabindex="-1"></a>treatment and PPVT scores was also significant</span>
<span id="cb58-709"><a href="#cb58-709" aria-hidden="true" tabindex="-1"></a>($b = 0.28, SE = 0.09, t(1074) = 3.06, p = .002$), suggesting that the</span>
<span id="cb58-710"><a href="#cb58-710" aria-hidden="true" tabindex="-1"></a>treatment effect varied as a function of initial vocabulary levels.</span>
<span id="cb58-711"><a href="#cb58-711" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-712"><a href="#cb58-712" aria-hidden="true" tabindex="-1"></a>Regarding random effects, we observe a variance of 25.01 ($SD = 5.00$)</span>
<span id="cb58-713"><a href="#cb58-713" aria-hidden="true" tabindex="-1"></a>for the intercepts across the different classrooms. This suggests there</span>
<span id="cb58-714"><a href="#cb58-714" aria-hidden="true" tabindex="-1"></a>is substantial variability in the baseline ETW scores that can be</span>
<span id="cb58-715"><a href="#cb58-715" aria-hidden="true" tabindex="-1"></a>attributed to differences between classrooms before considering</span>
<span id="cb58-716"><a href="#cb58-716" aria-hidden="true" tabindex="-1"></a>treatment or PPVT scores. The variance associated with the treatment</span>
<span id="cb58-717"><a href="#cb58-717" aria-hidden="true" tabindex="-1"></a>effect ($SD = 6.75$). This suggests significant variability in how the</span>
<span id="cb58-718"><a href="#cb58-718" aria-hidden="true" tabindex="-1"></a>treatment effect on ETW scores differs from across clasrooms. Finally,</span>
<span id="cb58-719"><a href="#cb58-719" aria-hidden="true" tabindex="-1"></a>the variance of residuals was 57.02 ($SD = 7.55$), indicating</span>
<span id="cb58-720"><a href="#cb58-720" aria-hidden="true" tabindex="-1"></a>within-classroom variance in student scores that cannot be explained by</span>
<span id="cb58-721"><a href="#cb58-721" aria-hidden="true" tabindex="-1"></a>the model's fixed effects or the classroom-level random effects.</span>
<span id="cb58-722"><a href="#cb58-722" aria-hidden="true" tabindex="-1"></a>Overall, our variance components are significant for both the random</span>
<span id="cb58-723"><a href="#cb58-723" aria-hidden="true" tabindex="-1"></a>intercept and slope for treatment. This suggests that multilevel</span>
<span id="cb58-724"><a href="#cb58-724" aria-hidden="true" tabindex="-1"></a>modeling is, indeed, appropriate and necessary to account for the</span>
<span id="cb58-725"><a href="#cb58-725" aria-hidden="true" tabindex="-1"></a>clustering of student scores within classrooms and the variability in</span>
<span id="cb58-726"><a href="#cb58-726" aria-hidden="true" tabindex="-1"></a>treatment effects across classrooms.</span>
<span id="cb58-727"><a href="#cb58-727" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-728"><a href="#cb58-728" aria-hidden="true" tabindex="-1"></a>the model estimated the standard deviation of the random intercepts for</span>
<span id="cb58-729"><a href="#cb58-729" aria-hidden="true" tabindex="-1"></a>classrooms ($SD = 5.00$), indicating variability in baseline ETW scores</span>
<span id="cb58-730"><a href="#cb58-730" aria-hidden="true" tabindex="-1"></a>across classrooms. The correlation between the random intercepts and</span>
<span id="cb58-731"><a href="#cb58-731" aria-hidden="true" tabindex="-1"></a>slopes for treatment within classrooms was estimated to be 0.89,</span>
<span id="cb58-732"><a href="#cb58-732" aria-hidden="true" tabindex="-1"></a>suggesting a strong positive relationship between the classroom baseline</span>
<span id="cb58-733"><a href="#cb58-733" aria-hidden="true" tabindex="-1"></a>scores and the treatment effect. The standard deviation of the random</span>
<span id="cb58-734"><a href="#cb58-734" aria-hidden="true" tabindex="-1"></a>slopes for treatment ($SD = 6.75$) indicated substantial variability in</span>
<span id="cb58-735"><a href="#cb58-735" aria-hidden="true" tabindex="-1"></a>the treatment effect across classrooms. The residual standard deviation</span>
<span id="cb58-736"><a href="#cb58-736" aria-hidden="true" tabindex="-1"></a>($SD = 7.55$) reflected the within-classroom variability in ETW scores</span>
<span id="cb58-737"><a href="#cb58-737" aria-hidden="true" tabindex="-1"></a>that was not explained by the model's fixed and random effects.</span>
<span id="cb58-738"><a href="#cb58-738" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-739"><a href="#cb58-739" aria-hidden="true" tabindex="-1"></a>Taken together, these results suggest that both the treatment and</span>
<span id="cb58-740"><a href="#cb58-740" aria-hidden="true" tabindex="-1"></a>initial PPVT scores are significant predictors of students' vocabulary</span>
<span id="cb58-741"><a href="#cb58-741" aria-hidden="true" tabindex="-1"></a>knowledge. There was a notable interaction effect, suggesting that the</span>
<span id="cb58-742"><a href="#cb58-742" aria-hidden="true" tabindex="-1"></a>benefit of the treatment varies depending on students' initial</span>
<span id="cb58-743"><a href="#cb58-743" aria-hidden="true" tabindex="-1"></a>vocabulary levels. The significant random effects for treatment across</span>
<span id="cb58-744"><a href="#cb58-744" aria-hidden="true" tabindex="-1"></a>classrooms underscore the intervention's differential effectiveness</span>
<span id="cb58-745"><a href="#cb58-745" aria-hidden="true" tabindex="-1"></a>depending on classroom context. These findings highlight the importance</span>
<span id="cb58-746"><a href="#cb58-746" aria-hidden="true" tabindex="-1"></a>of considering both the individual and contextual factors in educational</span>
<span id="cb58-747"><a href="#cb58-747" aria-hidden="true" tabindex="-1"></a>interventions. <span class="sc">\`\`\`</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>